-- Application ACL baseline for the public/private schemas. Revoke PostgreSQL's
-- default privileges before granting only the capabilities used by the API.

SET search_path = public, extensions;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public, private
  FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public, private
  FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public, private
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

REVOKE ALL ON SCHEMA private FROM PUBLIC, anonymous;
GRANT USAGE ON SCHEMA private TO authenticated, openexpert_service;
GRANT USAGE ON SCHEMA public TO anonymous, authenticated, openexpert_service;
REVOKE CREATE ON SCHEMA public FROM PUBLIC, anonymous, authenticated, openexpert_service;

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE ON TABLE public.booking_widget_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.administrative_role_permissions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.administrative_roles TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.appointment_calendar_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.appointment_resource_reservations TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.appointments TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.booking_outbox TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.booking_rate_limits TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.booking_services TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.booking_widget_services TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.booking_widgets TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.calendar_connections TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.client_account_links TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_activities TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_bank_applications TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_clients TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_contract_selections TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_item_settlements TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_items TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_multiform_drafts TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_offer_selections TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_offer_snapshots TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_participants TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_case_property_selections TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_cases TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_client_anonymization_execution_grants TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_client_anonymization_request_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_client_anonymization_requests TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_client_consent_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_client_people TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_clients TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_consent_definition_versions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_consent_definitions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_documents TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_eve_sessions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_item_submissions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_product_types TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_properties TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_property_images TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_providers TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_tasks TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_workflow_statuses TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.crm_workflows TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.expert_availability_overrides TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.expert_availability_rules TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.expert_brand_profiles TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.expert_time_off TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.external_busy_blocks TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facilities TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_images TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_memberships TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_opening_hours TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_opening_overrides TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_service_experts TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.facility_services TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mail_connections TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mail_send_requests TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_aliases TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_categories TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_chunks TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_embeddings TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_processing_jobs TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_products TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_file_versions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_files TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_override_revisions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_bank_overrides TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_banks TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_capacity_setting_revisions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_capacity_settings TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_catalog_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_drafts TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_override_revisions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_overrides TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_version_sources TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_version_variants TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_product_versions TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_products TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mortgage_source_documents TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_memberships TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_user_access_states TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_user_admin_roles TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_user_audit_events TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_user_direct_grants TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_user_preferences TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organizations TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.platform_user_roles TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.profiles TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.team_edges TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.team_facilities TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.team_memberships TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.teams TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.users TO openexpert_service;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.waitlist TO openexpert_service;
GRANT DELETE, INSERT, SELECT ON TABLE public.crm_documents TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.crm_property_images TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.mortgage_bank_overrides TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.mortgage_capacity_settings TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.mortgage_product_overrides TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.organization_memberships TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.team_facilities TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.team_memberships TO authenticated;
GRANT DELETE, INSERT, SELECT ON TABLE public.teams TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.booking_services TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.booking_widget_services TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.booking_widgets TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_activities TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_clients TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_item_settlements TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_items TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_multiform_drafts TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_offer_selections TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_participants TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_case_property_selections TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_cases TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_client_people TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_clients TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_item_submissions TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_properties TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.crm_tasks TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.expert_availability_overrides TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.expert_availability_rules TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.expert_brand_profiles TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facilities TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facility_memberships TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facility_opening_hours TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facility_opening_overrides TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facility_service_experts TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.facility_services TO authenticated;
GRANT DELETE, SELECT ON TABLE public.team_edges TO authenticated;
GRANT EXECUTE ON FUNCTION private.add_organization_member_by_email(target_organization_id uuid, target_email text, target_role text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.add_team_edge(target_organization_id uuid, target_parent_team_id uuid, target_child_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_access_crm_case_document(object_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_access_crm_case_document(object_name text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION private.can_access_crm_property_image(object_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_access_crm_property_image(object_name text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION private.can_access_facility_image(object_name text, require_manage boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_access_facility_image(object_name text, require_manage boolean) TO openexpert_service;
GRANT EXECUTE ON FUNCTION private.can_manage_booking_widget(target_organization_id uuid, target_facility_id uuid, target_fixed_expert_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_manage_mortgage_bank_logo(object_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_view_facility(target_organization_id uuid, target_facility_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_view_team(target_organization_id uuid, target_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.can_write_booking_widget(target_organization_id uuid, target_facility_id uuid, target_fixed_expert_user_id uuid, target_created_by_user_id uuid, target_booking_mode text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.create_organization_with_admin(organization_name text, requested_full_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.current_organization_id() TO authenticated;
GRANT EXECUTE ON FUNCTION private.has_administrative_permission(target_organization_id uuid, target_permission_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.has_facility_admin_membership(target_organization_id uuid, target_facility_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_facility_admin(target_organization_id uuid, target_facility_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_facility_member(target_organization_id uuid, target_facility_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_organization_admin(target_organization_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_organization_member(target_organization_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_organization_member(target_organization_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION private.is_super_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_team_admin(target_organization_id uuid, target_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.is_team_member(target_organization_id uuid, target_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.reject_mortgage_bank_file_event_mutation() TO PUBLIC;
GRANT EXECUTE ON FUNCTION private.shares_organization(target_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_can_view_client_privacy(target_organization_id uuid, target_client_id uuid, target_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_can_view_client_privacy(target_organization_id uuid, target_client_id uuid, target_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION private.user_has_administrative_permission(target_organization_id uuid, target_user_id uuid, target_permission_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.user_has_administrative_role(target_organization_id uuid, target_user_id uuid, target_role_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION private.validate_crm_case_bank_application_snapshot() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.add_organization_member_by_email(organization_id uuid, email text, role text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.add_team_edge(organization_id uuid, parent_team_id uuid, child_team_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.consume_booking_rate_limit(p_widget_token uuid, p_scope text, p_client_key text, p_limit integer, p_window_seconds integer) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_crm_case_bank_application(target_organization_id uuid, target_case_id uuid, target_offer_id uuid, target_property_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_crm_case_bank_application_snapshot(target_organization_id uuid, target_case_id uuid, target_offer_id uuid, target_property_id uuid, target_actor_user_id uuid, expected_property_updated_at timestamp with time zone, target_scenario_snapshot jsonb, target_calculation_snapshot jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_crm_case_simple(p_organization_id uuid, p_title text, p_client_ids uuid[], p_owner_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_crm_case_simple(p_organization_id uuid, p_title text, p_client_ids uuid[], p_owner_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_crm_client_anonymization_request(p_organization_id uuid, p_client_id uuid, p_subject_person_id uuid, p_request_channel text, p_requested_at timestamp with time zone, p_justification text, p_idempotency_key uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_crm_client_anonymization_request(p_organization_id uuid, p_client_id uuid, p_subject_person_id uuid, p_request_channel text, p_requested_at timestamp with time zone, p_justification text, p_idempotency_key uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_crm_client_with_consents(p_organization_id uuid, p_owner_user_id uuid, p_display_name text, p_status_code text, p_lead_source text, p_primary_email text, p_primary_phone text, p_tags text[], p_notes text, p_metadata jsonb, p_primary_person jsonb, p_consent_decisions jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_crm_consent_definition(p_organization_id uuid, p_code text, p_internal_name text, p_display_title text, p_content text, p_purpose text, p_channel text, p_legal_basis text, p_is_required boolean, p_status text, p_sort_order integer, p_language_code text, p_effective_from timestamp with time zone, p_effective_to timestamp with time zone, p_change_note text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_delegated_crm_task(p_request jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_mortgage_product_draft_v2(p_bank_id uuid, p_slug text, p_name text, p_category text, p_distribution_channel text, p_draft_data jsonb, p_actor_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_organization_with_admin(organization_name text, full_name text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_staff_appointment(p_organization_id uuid, p_facility_id uuid, p_service_id uuid, p_expert_user_id uuid, p_client_id uuid, p_client_person_id uuid, p_starts_at timestamp with time zone, p_notes text, p_created_by_user_id uuid, p_idempotency_key text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_staff_appointment(p_organization_id uuid, p_facility_id uuid, p_service_id uuid, p_expert_user_id uuid, p_client_id uuid, p_client_person_id uuid, p_starts_at timestamp with time zone, p_notes text, p_created_by_user_id uuid, p_idempotency_key text, p_meeting_mode text, p_meeting_url text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.create_widget_booking(p_widget_token uuid, p_service_id uuid, p_starts_at timestamp with time zone, p_customer_name text, p_customer_email text, p_idempotency_key text, p_customer_phone text, p_expert_user_id uuid, p_notes text, p_consent_decisions jsonb, p_booking_context jsonb, p_request_fingerprint text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.crm_omnisearch_normalize(input text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.execute_crm_client_anonymization_request(p_organization_id uuid, p_request_id uuid, p_grant_id uuid, p_expected_revision bigint, p_idempotency_key uuid, p_confirmation text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_booking_widget_analytics(p_organization_id uuid, p_widget_id uuid, p_from date, p_to date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_booking_widget_analytics(p_organization_id uuid, p_widget_id uuid, p_from date, p_to date) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.get_booking_widget_catalog(p_widget_token uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.get_booking_widget_slots(p_widget_token uuid, p_service_id uuid, p_starts_on date, p_ends_on date, p_expert_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.get_organization_user_admin_access(p_organization_id uuid, p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_personal_booking_widget_counts(p_organization_id uuid, p_expert_user_id uuid, p_since timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_personal_booking_widget_counts(p_organization_id uuid, p_expert_user_id uuid, p_since timestamp with time zone) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.get_staff_booking_slots(p_organization_id uuid, p_facility_id uuid, p_service_id uuid, p_local_date date, p_expert_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.publish_mortgage_document_template_draft(p_bank_id uuid, p_template_key text, p_expected_revision bigint, p_actor_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.publish_mortgage_product_draft(p_product_id uuid, p_expected_revision bigint, p_actor_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.record_booking_widget_event(p_widget_token uuid, p_visit_id uuid, p_event_type text, p_service_id uuid, p_event_id text, p_is_embedded boolean) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.replace_calendar_busy_blocks(p_organization_id uuid, p_connection_id uuid, p_blocks jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.replace_expert_availability(p_organization_id uuid, p_facility_id uuid, p_user_id uuid, p_rules jsonb, p_overrides jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_expert_availability(p_organization_id uuid, p_facility_id uuid, p_user_id uuid, p_rules jsonb, p_overrides jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.replace_facility_opening_hours(p_organization_id uuid, p_facility_id uuid, p_hours jsonb, p_overrides jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.replace_facility_opening_hours(p_organization_id uuid, p_facility_id uuid, p_hours jsonb, p_overrides jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.replay_widget_booking(p_widget_token uuid, p_idempotency_key text, p_request_fingerprint text) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.request_crm_client_anonymization_execution_grant(p_organization_id uuid, p_request_id uuid, p_grantee_user_id uuid, p_approver_user_id uuid, p_justification text, p_expires_at timestamp with time zone, p_idempotency_key uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.respond_crm_client_anonymization_execution_grant(p_organization_id uuid, p_grant_id uuid, p_expected_revision bigint, p_action text, p_reason text, p_idempotency_key uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_crm_client_anonymization_execution_grant(p_organization_id uuid, p_grant_id uuid, p_expected_revision bigint, p_reason text, p_idempotency_key uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_mortgage_document_template_draft(p_bank_id uuid, p_template_key text, p_label text, p_source_file_name text, p_source_sha256 text, p_registry_version integer, p_template_json jsonb, p_validation_report jsonb, p_expected_revision bigint, p_actor_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.save_mortgage_product_draft_v2(p_product_id uuid, p_expected_revision bigint, p_draft_data jsonb, p_actor_user_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.search_crm_cases(p_organization_id uuid, p_filters jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_crm_cases(p_organization_id uuid, p_filters jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.search_crm_cases_with_context(p_organization_id uuid, p_filters jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_crm_cases_with_context(p_organization_id uuid, p_filters jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.search_crm_clients(p_organization_id uuid, p_filters jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_crm_clients(p_organization_id uuid, p_filters jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.search_crm_clients_ranked(p_organization_id uuid, p_filters jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_crm_clients_ranked(p_organization_id uuid, p_filters jsonb) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.search_crm_omnisearch(p_organization_id uuid, p_query text, p_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_mortgage_bank_file_chunks(query_text text, query_embedding extensions.vector, filter_bank_id uuid, filter_category_key text, filter_mime_group text, filter_product_id uuid, filter_status text, match_count integer, full_text_weight double precision, semantic_weight double precision, rrf_k integer) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.set_crm_case_clients(p_organization_id uuid, p_case_id uuid, p_client_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_crm_case_clients(p_organization_id uuid, p_case_id uuid, p_client_ids uuid[]) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.set_facility_cover_image(p_organization_id uuid, p_facility_id uuid, p_image_id uuid) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.set_organization_user_admin_access(p_organization_id uuid, p_user_id uuid, p_expected_revision bigint, p_idempotency_key uuid, p_role_keys text[], p_consent_publish boolean, p_consent_justification text, p_consent_expires_at timestamp with time zone, p_change_reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.sign_crm_case_contract(target_organization_id uuid, target_case_id uuid, target_application_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_booking_widget_configuration(p_organization_id uuid, p_facility_id uuid, p_widget_id uuid, p_widget_patch jsonb, p_update_services boolean, p_service_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_booking_widget_configuration(p_organization_id uuid, p_facility_id uuid, p_widget_id uuid, p_widget_patch jsonb, p_update_services boolean, p_service_ids uuid[]) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.update_crm_consent_definition(p_definition_id uuid, p_organization_id uuid, p_internal_name text, p_display_title text, p_content text, p_purpose text, p_channel text, p_legal_basis text, p_is_required boolean, p_status text, p_sort_order integer, p_language_code text, p_effective_from timestamp with time zone, p_effective_to timestamp with time zone, p_change_note text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_facility_service_configuration(p_organization_id uuid, p_facility_id uuid, p_service_id uuid, p_service_patch jsonb, p_update_availability boolean, p_is_available boolean, p_update_experts boolean, p_expert_user_ids uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_facility_service_configuration(p_organization_id uuid, p_facility_id uuid, p_service_id uuid, p_service_patch jsonb, p_update_availability boolean, p_is_available boolean, p_update_experts boolean, p_expert_user_ids uuid[]) TO openexpert_service;
GRANT INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organization_design_settings TO authenticated;
GRANT INSERT, SELECT ON TABLE public.crm_case_contract_selections TO authenticated;
GRANT INSERT, SELECT ON TABLE public.crm_client_consent_events TO authenticated;
GRANT INSERT, SELECT ON TABLE public.crm_consent_definition_versions TO authenticated;
GRANT INSERT, SELECT ON TABLE public.crm_consent_definitions TO authenticated;
GRANT REFERENCES, TRIGGER, TRUNCATE ON TABLE public.organization_design_settings TO openexpert_service;
GRANT SELECT ON TABLE public.administrative_role_permissions TO authenticated;
GRANT SELECT ON TABLE public.administrative_roles TO authenticated;
GRANT SELECT ON TABLE public.appointments TO authenticated;
GRANT SELECT ON TABLE public.client_account_links TO authenticated;
GRANT SELECT ON TABLE public.crm_case_bank_applications TO authenticated;
GRANT SELECT ON TABLE public.crm_case_offer_snapshots TO authenticated;
GRANT SELECT ON TABLE public.crm_client_anonymization_execution_grants TO authenticated;
GRANT SELECT ON TABLE public.crm_client_anonymization_request_events TO authenticated;
GRANT SELECT ON TABLE public.crm_client_anonymization_requests TO authenticated;
GRANT SELECT ON TABLE public.crm_eve_sessions TO authenticated;
GRANT SELECT ON TABLE public.crm_product_types TO authenticated;
GRANT SELECT ON TABLE public.crm_providers TO authenticated;
GRANT SELECT ON TABLE public.crm_workflow_statuses TO authenticated;
GRANT SELECT ON TABLE public.crm_workflows TO authenticated;
GRANT SELECT ON TABLE public.facility_images TO authenticated;
GRANT SELECT ON TABLE public.mortgage_bank_aliases TO authenticated;
GRANT SELECT ON TABLE public.mortgage_bank_override_revisions TO authenticated;
GRANT SELECT ON TABLE public.mortgage_banks TO authenticated;
GRANT SELECT ON TABLE public.mortgage_capacity_setting_revisions TO authenticated;
GRANT SELECT ON TABLE public.mortgage_document_template_revisions TO openexpert_service;
GRANT SELECT ON TABLE public.mortgage_document_templates TO openexpert_service;
GRANT SELECT ON TABLE public.mortgage_product_override_revisions TO authenticated;
GRANT SELECT ON TABLE public.mortgage_product_version_document_templates TO openexpert_service;
GRANT SELECT ON TABLE public.mortgage_product_version_sources TO authenticated;
GRANT SELECT ON TABLE public.mortgage_product_version_variants TO authenticated;
GRANT SELECT ON TABLE public.mortgage_product_versions TO authenticated;
GRANT SELECT ON TABLE public.mortgage_products TO authenticated;
GRANT SELECT ON TABLE public.mortgage_source_documents TO authenticated;
GRANT SELECT ON TABLE public.organization_user_access_states TO authenticated;
GRANT SELECT ON TABLE public.organization_user_admin_roles TO authenticated;
GRANT SELECT ON TABLE public.organization_user_audit_events TO authenticated;
GRANT SELECT ON TABLE public.organization_user_direct_grants TO authenticated;
GRANT SELECT ON TABLE public.organizations TO authenticated;
GRANT SELECT ON TABLE public.platform_user_roles TO authenticated;
GRANT SELECT ON TABLE public.profiles TO authenticated;
GRANT SELECT ON TABLE public.users TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.booking_outbox_id_seq TO openexpert_service;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.booking_widget_events_id_seq TO openexpert_service;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.mortgage_bank_file_chunks_id_seq TO openexpert_service;
GRANT UPDATE ON SEQUENCE public.booking_outbox_id_seq TO authenticated;
GRANT UPDATE ON SEQUENCE public.mortgage_bank_file_chunks_id_seq TO authenticated;

RESET search_path;
