-- OpenExpert Bank is an explicitly synthetic institution used to exercise the
-- real mortgage application and inbound-mail flows without integrating an
-- external bank. The marker is catalog-level so mock-only behavior never has
-- to rely on a mutable display name.

ALTER TABLE public.mortgage_banks
  ADD COLUMN IF NOT EXISTS is_mock boolean;

UPDATE public.mortgage_banks
SET is_mock = false
WHERE is_mock IS NULL;

ALTER TABLE public.mortgage_banks
  ALTER COLUMN is_mock SET DEFAULT false,
  ALTER COLUMN is_mock SET NOT NULL;

COMMENT ON COLUMN public.mortgage_banks.is_mock IS
  'True only for synthetic institutions whose application responses are generated by OpenExpert for demonstrations and automated flow verification.';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.mortgage_banks AS bank
    WHERE bank.slug = 'openexpert-bank'
      AND NOT bank.is_mock
  ) THEN
    RAISE EXCEPTION 'openexpert_mock_bank_slug_is_owned_by_a_real_bank'
      USING errcode = '23505';
  END IF;
END;
$$;

INSERT INTO public.mortgage_banks (
  slug,
  name,
  website_url,
  logo_url,
  logo_background_color,
  brand_color,
  brand_foreground_color,
  is_mock
)
VALUES (
  'openexpert-bank',
  'OpenExpert Bank',
  'https://openexpert.app',
  'https://crm.openexpert.app/assets/openexpert-bank.svg',
  '#FFFFFF',
  '#111827',
  '#FFFFFF',
  true
)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    website_url = EXCLUDED.website_url,
    logo_url = EXCLUDED.logo_url,
    logo_background_color = EXCLUDED.logo_background_color,
    brand_color = EXCLUDED.brand_color,
    brand_foreground_color = EXCLUDED.brand_foreground_color,
    is_mock = true,
    updated_at = statement_timestamp()
WHERE (
  public.mortgage_banks.name,
  public.mortgage_banks.website_url,
  public.mortgage_banks.logo_url,
  public.mortgage_banks.logo_background_color,
  public.mortgage_banks.brand_color,
  public.mortgage_banks.brand_foreground_color,
  public.mortgage_banks.is_mock
) IS DISTINCT FROM (
  EXCLUDED.name,
  EXCLUDED.website_url,
  EXCLUDED.logo_url,
  EXCLUDED.logo_background_color,
  EXCLUDED.brand_color,
  EXCLUDED.brand_foreground_color,
  EXCLUDED.is_mock
);

INSERT INTO public.mortgage_products (
  bank_id,
  slug,
  name,
  category,
  distribution_channel,
  is_active,
  product_kind,
  archived_at,
  archived_by_user_id
)
SELECT
  bank.id,
  'hipoteka-demo-stala-5-lat',
  'Hipoteka Demo – stała stopa przez 5 lat',
  'housing',
  'bank_public_website',
  true,
  'mortgage',
  NULL,
  NULL
FROM public.mortgage_banks AS bank
WHERE bank.slug = 'openexpert-bank'
ON CONFLICT (bank_id, slug) DO UPDATE
SET name = EXCLUDED.name,
    category = EXCLUDED.category,
    distribution_channel = EXCLUDED.distribution_channel,
    is_active = true,
    product_kind = EXCLUDED.product_kind,
    archived_at = NULL,
    archived_by_user_id = NULL,
    revision = public.mortgage_products.revision + 1
WHERE (
  public.mortgage_products.name,
  public.mortgage_products.category,
  public.mortgage_products.distribution_channel,
  public.mortgage_products.is_active,
  public.mortgage_products.product_kind,
  public.mortgage_products.archived_at,
  public.mortgage_products.archived_by_user_id
) IS DISTINCT FROM (
  EXCLUDED.name,
  EXCLUDED.category,
  EXCLUDED.distribution_channel,
  EXCLUDED.is_active,
  EXCLUDED.product_kind,
  EXCLUDED.archived_at,
  EXCLUDED.archived_by_user_id
);

-- The legacy-v1 insert path intentionally creates the standard calculator
-- variant and makes this publication current through the existing catalogue
-- triggers. All calculation inputs are known so the demo offer is immediately
-- usable in comparisons and can be saved to a case.
INSERT INTO public.mortgage_product_versions (
  version_key,
  product_id,
  effective_from,
  effective_to,
  retrieved_at,
  calculation_date,
  data_status,
  completeness_score,
  interest_type,
  fixed_rate_pct,
  fixed_period_months,
  margin_pct,
  reference_rate_code,
  reference_rate_pct,
  reference_rate_as_of,
  representative_apr_pct,
  min_amount,
  max_amount,
  min_term_months,
  max_term_months,
  max_ltv_pct,
  is_eco,
  cost_rules,
  requirements,
  representative_example,
  assumptions,
  unknown_fields,
  document_requirements,
  multiform_template_ids,
  lifecycle_status,
  calculator_schema_version,
  calculator_engine_version,
  validation_report
)
SELECT
  'openexpert-bank-hipoteka-demo-stala-5-lat-v1',
  product.id,
  DATE '2026-01-01',
  NULL,
  TIMESTAMPTZ '2026-08-19 00:00:00+02',
  DATE '2026-08-19',
  'confirmed',
  100,
  'fixed_periodic',
  5.89000,
  60,
  1.85000,
  'WIBOR 3M',
  4.75000,
  DATE '2026-08-18',
  6.42000,
  100000.00,
  2000000.00,
  60,
  420,
  90.0000,
  false,
  jsonb_build_object(
    'commissionPct', 0,
    'appraisalFee', 500,
    'pccFee', 19,
    'courtFee', 200,
    'accountMonthlyFee', 0,
    'cardMonthlyFee', 0,
    'propertyInsuranceAnnualRatePct', 0.08,
    'lifeInsuranceMonthlyRatePct', 0.03,
    'lifeInsuranceMonths', 60
  ),
  jsonb_build_array(
    'Rachunek osobisty OpenExpert Bank',
    'Miesięczny wpływ wynagrodzenia na rachunek',
    'Ubezpieczenie nieruchomości przez cały okres kredytowania'
  ),
  jsonb_build_object(
    'loanAmount', 400000,
    'propertyValue', 500000,
    'ltvPct', 80,
    'termMonths', 300,
    'installment', 2550.29,
    'representativeAprPct', 6.42
  ),
  jsonb_build_array(
    'Oferta jest syntetyczna i służy wyłącznie do demonstracji przepływu OpenExpert.',
    'Po 60 miesiącach kalkulacja przyjmuje WIBOR 3M powiększony o marżę 1,85 p.p.'
  ),
  ARRAY[]::text[],
  '[]'::jsonb,
  ARRAY[]::text[],
  'published',
  1,
  'legacy-flat-v1',
  jsonb_build_object(
    'valid', true,
    'issues', '[]'::jsonb,
    'source', 'openexpert_mock_bank_migration'
  )
FROM public.mortgage_products AS product
JOIN public.mortgage_banks AS bank ON bank.id = product.bank_id
WHERE bank.slug = 'openexpert-bank'
  AND product.slug = 'hipoteka-demo-stala-5-lat'
  AND NOT EXISTS (
    SELECT 1
    FROM public.mortgage_product_versions AS existing_version
    WHERE existing_version.version_key =
      'openexpert-bank-hipoteka-demo-stala-5-lat-v1'
  );

-- Applications created from a synthetic institution receive a stable,
-- human-readable bank reference. The six-digit suffix is the first uint32 of
-- SHA-256(lowercase UUID), interpreted big-endian and reduced modulo 1,000,000.
-- The document generator uses the same algorithm, so the PDF, attachment and
-- CRM application always carry the same number without storing another secret.
CREATE FUNCTION private.crm_mock_bank_application_reference(
  p_application_id uuid,
  p_created_at timestamptz
) RETURNS text
  LANGUAGE sql
  STABLE
  STRICT
  SET search_path TO ''
  AS $$
    WITH digest_bytes AS (
      SELECT extensions.digest(
        convert_to(lower(p_application_id::text), 'UTF8'),
        'sha256'
      ) AS value
    )
    SELECT format(
      'OEB-%s-%s',
      to_char(
        (p_created_at AT TIME ZONE 'Europe/Warsaw')::date,
        'YYYYMMDD'
      ),
      lpad((
        (
          get_byte(value, 0)::bigint * 16777216
          + get_byte(value, 1)::bigint * 65536
          + get_byte(value, 2)::bigint * 256
          + get_byte(value, 3)::bigint
        ) % 1000000
      )::text, 6, '0')
    )
    FROM digest_bytes;
  $$;

COMMENT ON FUNCTION private.crm_mock_bank_application_reference(
  uuid, timestamptz
) IS
  'Builds OEB-YYYYMMDD-###### from Warsaw creation date and the first big-endian uint32 of SHA-256(lowercase application UUID), modulo one million.';

REVOKE ALL ON FUNCTION private.crm_mock_bank_application_reference(
  uuid, timestamptz
) FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE FUNCTION private.assign_crm_mock_bank_application_reference()
RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.mortgage_banks AS bank
    WHERE bank.id = NEW.bank_id
      AND bank.is_mock
  ) THEN
    UPDATE public.crm_item_submissions AS submission
    SET external_reference = private.crm_mock_bank_application_reference(
      NEW.submission_id,
      NEW.created_at
    )
    WHERE submission.organization_id = NEW.organization_id
      AND submission.case_item_id = NEW.case_item_id
      AND submission.id = NEW.submission_id
      AND submission.external_reference IS DISTINCT FROM
        private.crm_mock_bank_application_reference(
          NEW.submission_id,
          NEW.created_at
        );
  END IF;

  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION private.assign_crm_mock_bank_application_reference() IS
  'Assigns a stable OEB date/UUID reference to newly created applications for any explicitly marked mock institution.';

REVOKE ALL ON FUNCTION private.assign_crm_mock_bank_application_reference()
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE TRIGGER crm_case_bank_applications_assign_mock_reference
  AFTER INSERT ON public.crm_case_bank_applications
  FOR EACH ROW
  EXECUTE FUNCTION private.assign_crm_mock_bank_application_reference();

UPDATE public.crm_item_submissions AS submission
SET external_reference = private.crm_mock_bank_application_reference(
  application.submission_id,
  application.created_at
)
FROM public.crm_case_bank_applications AS application
JOIN public.mortgage_banks AS bank ON bank.id = application.bank_id
WHERE bank.is_mock
  AND submission.organization_id = application.organization_id
  AND submission.case_item_id = application.case_item_id
  AND submission.id = application.submission_id
  AND submission.external_reference IS DISTINCT FROM
    private.crm_mock_bank_application_reference(
      application.submission_id,
      application.created_at
    );

CREATE UNIQUE INDEX crm_item_submissions_openexpert_mock_reference_key
  ON public.crm_item_submissions (organization_id, external_reference)
  WHERE external_reference ~ '^OEB-[0-9]{8}-[0-9]{6}$';

COMMENT ON INDEX public.crm_item_submissions_openexpert_mock_reference_key IS
  'Reserves OEB references for unambiguous tenant-local mock-bank mail correlation; hash collisions fail explicitly.';

-- A generation-stable delivery ledger. The encrypted archive and a strict
-- JSON manifest containing the exact provider request live in the dedicated
-- private object-store namespace. The database retains only opaque paths,
-- checksums, sizes and delivery state; the PESEL password is never persisted.
CREATE TABLE public.crm_mock_bank_dispatches (
  id uuid PRIMARY KEY,
  organization_id uuid NOT NULL,
  case_id uuid NOT NULL,
  application_id uuid NOT NULL,
  kind text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  generation integer DEFAULT 1 NOT NULL,
  generation_started_at timestamptz NOT NULL,
  attempts integer DEFAULT 1 NOT NULL,
  request_id uuid NOT NULL,
  requested_by_user_id uuid,
  recipient_connection_id uuid,
  payload_id uuid NOT NULL,
  manifest_storage_bucket text DEFAULT 'crm-mock-bank-outbox'::text NOT NULL,
  manifest_storage_path text NOT NULL,
  manifest_sha256 text,
  manifest_size_bytes integer,
  archive_storage_bucket text DEFAULT 'crm-mock-bank-outbox'::text NOT NULL,
  archive_storage_path text NOT NULL,
  archive_sha256 text,
  archive_size_bytes integer,
  payload_sha256 text,
  payload_ready_at timestamptz,
  provider_message_id text,
  error_code text,
  last_attempt_at timestamptz NOT NULL,
  lease_expires_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT crm_mock_bank_dispatches_application_kind_key
    UNIQUE (application_id, kind),
  CONSTRAINT crm_mock_bank_dispatches_request_key UNIQUE (request_id),
  CONSTRAINT crm_mock_bank_dispatches_kind_check CHECK (
    kind IN ('esis', 'credit_decision')
  ),
  CONSTRAINT crm_mock_bank_dispatches_status_check CHECK (
    status IN ('pending', 'sent', 'failed')
  ),
  CONSTRAINT crm_mock_bank_dispatches_generation_check CHECK (generation >= 1),
  CONSTRAINT crm_mock_bank_dispatches_attempts_check CHECK (attempts >= 1),
  CONSTRAINT crm_mock_bank_dispatches_storage_bucket_check CHECK (
    manifest_storage_bucket = 'crm-mock-bank-outbox'::text
    AND archive_storage_bucket = 'crm-mock-bank-outbox'::text
  ),
  CONSTRAINT crm_mock_bank_dispatches_storage_path_check CHECK (
    manifest_storage_path = organization_id::text || '/' ||
      application_id::text || '/' || id::text || '/' || kind || '/generation-' ||
      generation::text || '-' || payload_id::text || '.json'
    AND archive_storage_path = organization_id::text || '/' ||
      application_id::text || '/' || id::text || '/' || kind || '/generation-' ||
      generation::text || '-' || payload_id::text || '.zip'
    AND char_length(manifest_storage_path) <= 1024
    AND char_length(archive_storage_path) <= 1024
  ),
  CONSTRAINT crm_mock_bank_dispatches_payload_state_check CHECK (
    (
      manifest_sha256 IS NULL
      AND manifest_size_bytes IS NULL
      AND archive_sha256 IS NULL
      AND archive_size_bytes IS NULL
      AND payload_sha256 IS NULL
      AND payload_ready_at IS NULL
    ) OR (
      manifest_sha256 ~ '^[0-9a-f]{64}$'
      AND manifest_size_bytes BETWEEN 1 AND 5242880
      AND archive_sha256 ~ '^[0-9a-f]{64}$'
      AND archive_size_bytes BETWEEN 1 AND 5242880
      AND payload_sha256 ~ '^[0-9a-f]{64}$'
      AND payload_ready_at IS NOT NULL
    )
  ),
  CONSTRAINT crm_mock_bank_dispatches_provider_id_check CHECK (
    provider_message_id IS NULL OR (
      provider_message_id = btrim(provider_message_id)
      AND provider_message_id <> ''
      AND char_length(provider_message_id) <= 512
      AND provider_message_id !~ '[[:cntrl:]]'
    )
  ),
  CONSTRAINT crm_mock_bank_dispatches_error_code_check CHECK (
    error_code IS NULL OR (
      char_length(error_code) <= 100
      AND error_code ~ '^[a-z0-9]+([._-][a-z0-9]+)*$'
    )
  ),
  CONSTRAINT crm_mock_bank_dispatches_state_check CHECK (
    (
      status = 'pending'
      AND lease_expires_at IS NOT NULL
      AND provider_message_id IS NULL
      AND error_code IS NULL
      AND sent_at IS NULL
      AND failed_at IS NULL
    ) OR (
      status = 'sent'
      AND lease_expires_at IS NULL
      AND provider_message_id IS NOT NULL
      AND error_code IS NULL
      AND sent_at IS NOT NULL
      AND failed_at IS NULL
      AND payload_ready_at IS NOT NULL
    ) OR (
      status = 'failed'
      AND lease_expires_at IS NULL
      AND provider_message_id IS NULL
      AND error_code IS NOT NULL
      AND sent_at IS NULL
      AND failed_at IS NOT NULL
    )
  ),
  CONSTRAINT crm_mock_bank_dispatches_timestamps_check CHECK (
    isfinite(generation_started_at)
    AND isfinite(last_attempt_at)
    AND isfinite(created_at)
    AND isfinite(updated_at)
    AND (payload_ready_at IS NULL OR isfinite(payload_ready_at))
    AND (lease_expires_at IS NULL OR isfinite(lease_expires_at))
    AND (sent_at IS NULL OR isfinite(sent_at))
    AND (failed_at IS NULL OR isfinite(failed_at))
    AND generation_started_at >= created_at
    AND updated_at >= created_at
    AND last_attempt_at >= generation_started_at
    AND (payload_ready_at IS NULL OR payload_ready_at >= generation_started_at)
    AND (lease_expires_at IS NULL OR lease_expires_at > last_attempt_at)
    AND (sent_at IS NULL OR sent_at >= last_attempt_at)
    AND (failed_at IS NULL OR failed_at >= last_attempt_at)
  ),
  CONSTRAINT crm_mock_bank_dispatches_application_fk
    FOREIGN KEY (organization_id, case_id, application_id)
    REFERENCES public.crm_case_bank_applications
      (organization_id, case_id, submission_id)
    ON DELETE CASCADE,
  CONSTRAINT crm_mock_bank_dispatches_requested_actor_fk
    FOREIGN KEY (organization_id, requested_by_user_id)
    REFERENCES public.organization_memberships (organization_id, user_id)
    ON DELETE SET NULL (requested_by_user_id),
  CONSTRAINT crm_mock_bank_dispatches_recipient_connection_fk
    FOREIGN KEY (
      organization_id,
      requested_by_user_id,
      recipient_connection_id
    )
    REFERENCES public.mail_connections (organization_id, owner_user_id, id)
    ON DELETE SET NULL (recipient_connection_id)
);

COMMENT ON TABLE public.crm_mock_bank_dispatches IS
  'Server-only generation/lease ledger for exact replay of synthetic bank mail. Full message metadata and encrypted ZIP bytes live in private object storage.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.generation IS
  'Monotonic business generation. Ordinary failed/expired retries never change it; explicit force resend after sent does.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.generation_started_at IS
  'Stable issue-time source for every PDF retry in one generation.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.attempts IS
  'Number of exclusive leases issued within the current generation.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.request_id IS
  'Opaque per-attempt capability required to commit payload metadata or finalize the current lease.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.payload_sha256 IS
  'SHA-256 over the exact persisted manifest bytes plus exact encrypted archive bytes.';
COMMENT ON COLUMN public.crm_mock_bank_dispatches.error_code IS
  'Privacy-safe machine code only; provider messages and document content are forbidden.';

CREATE INDEX crm_mock_bank_dispatches_scope_idx
  ON public.crm_mock_bank_dispatches (
    organization_id,
    case_id,
    application_id,
    kind
  );

CREATE TRIGGER crm_mock_bank_dispatches_set_updated_at
  BEFORE UPDATE ON public.crm_mock_bank_dispatches
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- A provider call happens outside the database transaction that owns the
-- reservation. Keep the referenced application and its authoritative stage
-- stable for the short lease so a concurrent delete/transition cannot erase
-- the ledger after the provider has accepted the message.
CREATE FUNCTION private.guard_crm_mock_bank_application_delete_during_delivery()
RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.crm_mock_bank_dispatches AS dispatch
    WHERE dispatch.organization_id = OLD.organization_id
      AND dispatch.case_id = OLD.case_id
      AND dispatch.application_id = OLD.submission_id
      AND dispatch.status = 'pending'
      AND dispatch.lease_expires_at > clock_timestamp()
  ) THEN
    RAISE EXCEPTION 'crm_mock_bank_delivery_lease_active'
      USING errcode = '55000';
  END IF;
  RETURN OLD;
END;
$$;

REVOKE ALL ON FUNCTION private.guard_crm_mock_bank_application_delete_during_delivery()
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE TRIGGER crm_case_bank_applications_guard_mock_delivery_delete
  BEFORE DELETE ON public.crm_case_bank_applications
  FOR EACH ROW
  EXECUTE FUNCTION private.guard_crm_mock_bank_application_delete_during_delivery();

CREATE FUNCTION private.guard_crm_mock_bank_process_transition_during_delivery()
RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
BEGIN
  IF NEW.stage IS DISTINCT FROM OLD.stage
    AND EXISTS (
      SELECT 1
      FROM public.crm_mock_bank_dispatches AS dispatch
      WHERE dispatch.organization_id = OLD.organization_id
        AND dispatch.case_id = OLD.case_id
        AND dispatch.application_id = OLD.application_id
        AND dispatch.status = 'pending'
        AND dispatch.lease_expires_at > clock_timestamp()
    )
  THEN
    RAISE EXCEPTION 'crm_mock_bank_delivery_lease_active'
      USING errcode = '55000';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.guard_crm_mock_bank_process_transition_during_delivery()
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE TRIGGER crm_mortgage_processes_guard_mock_delivery_transition
  BEFORE UPDATE OF stage ON public.crm_mortgage_application_processes
  FOR EACH ROW
  EXECUTE FUNCTION private.guard_crm_mock_bank_process_transition_during_delivery();

CREATE FUNCTION private.crm_mock_bank_dispatch_response(
  p_dispatch_id uuid,
  p_application_reference text,
  p_state text,
  p_should_send boolean
) RETURNS jsonb
  LANGUAGE sql
  STABLE
  SET search_path TO ''
  AS $$
    SELECT jsonb_build_object(
      'dispatchId', dispatch.id,
      'applicationId', dispatch.application_id,
      'applicationNumber', p_application_reference,
      'kind', dispatch.kind,
      'state', p_state,
      'shouldSend', p_should_send,
      'generation', dispatch.generation,
      'generationStartedAt', dispatch.generation_started_at,
      'attempts', dispatch.attempts,
      'createdAt', dispatch.created_at,
      'leaseExpiresAt', dispatch.lease_expires_at,
      'recipientConnectionId', dispatch.recipient_connection_id,
      'payloadId', dispatch.payload_id,
      'manifestStorageBucket', dispatch.manifest_storage_bucket,
      'manifestStoragePath', dispatch.manifest_storage_path,
      'manifestSha256', dispatch.manifest_sha256,
      'manifestSizeBytes', dispatch.manifest_size_bytes,
      'archiveStorageBucket', dispatch.archive_storage_bucket,
      'archiveStoragePath', dispatch.archive_storage_path,
      'archiveSha256', dispatch.archive_sha256,
      'archiveSizeBytes', dispatch.archive_size_bytes,
      'payloadSha256', dispatch.payload_sha256,
      'payloadReadyAt', dispatch.payload_ready_at,
      'providerMessageId', dispatch.provider_message_id,
      'errorCode', dispatch.error_code,
      'sentAt', dispatch.sent_at,
      'failedAt', dispatch.failed_at
    )
    FROM public.crm_mock_bank_dispatches AS dispatch
    WHERE dispatch.id = p_dispatch_id;
  $$;

REVOKE ALL ON FUNCTION private.crm_mock_bank_dispatch_response(
  uuid, text, text, boolean
) FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE FUNCTION public.reserve_crm_mock_bank_dispatch(
  p_organization_id uuid,
  p_case_id uuid,
  p_application_id uuid,
  p_kind text,
  p_request_id uuid,
  p_requested_by_user_id uuid,
  p_recipient_connection_id uuid,
  p_force_resend boolean DEFAULT false
) RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  membership_role text;
  case_owner_user_id uuid;
  item_owner_user_id uuid;
  application_reference text;
  canonical_application_reference text;
  process_stage text;
  dispatch_row public.crm_mock_bank_dispatches%rowtype;
  lease_now timestamptz := clock_timestamp();
  next_dispatch_id uuid;
  next_payload_id uuid;
  next_generation integer;
BEGIN
  IF p_organization_id IS NULL
    OR p_case_id IS NULL
    OR p_application_id IS NULL
    OR p_request_id IS NULL
    OR p_requested_by_user_id IS NULL
    OR p_recipient_connection_id IS NULL
    OR p_kind IS NULL
    OR p_kind NOT IN ('esis', 'credit_decision')
    OR p_force_resend IS NULL
  THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_dispatch_reservation'
      USING errcode = '22023';
  END IF;

  -- Match the lifecycle lock order and validate the authoritative stage under
  -- the same locks that protect a new delivery claim.
  SELECT
    membership.role,
    crm_case.owner_user_id,
    item.owner_user_id,
    submission.external_reference,
    private.crm_mock_bank_application_reference(
      application.submission_id,
      application.created_at
    ),
    process.stage
  INTO
    membership_role,
    case_owner_user_id,
    item_owner_user_id,
    application_reference,
    canonical_application_reference,
    process_stage
  FROM public.crm_case_bank_applications AS application
  JOIN public.mortgage_banks AS bank
    ON bank.id = application.bank_id
   AND bank.is_mock
  JOIN public.crm_cases AS crm_case
    ON crm_case.organization_id = application.organization_id
   AND crm_case.id = application.case_id
  JOIN public.crm_case_items AS item
    ON item.organization_id = application.organization_id
   AND item.case_id = application.case_id
   AND item.id = application.case_item_id
  JOIN public.crm_item_submissions AS submission
    ON submission.organization_id = application.organization_id
   AND submission.case_item_id = application.case_item_id
   AND submission.id = application.submission_id
  JOIN public.crm_mortgage_application_processes AS process
    ON process.organization_id = application.organization_id
   AND process.case_id = application.case_id
   AND process.application_id = application.submission_id
  JOIN public.organization_memberships AS membership
    ON membership.organization_id = application.organization_id
   AND membership.user_id = p_requested_by_user_id
  WHERE application.organization_id = p_organization_id
    AND application.case_id = p_case_id
    AND application.submission_id = p_application_id
  FOR UPDATE OF application, process;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'crm_mock_bank_application_scope_or_membership_not_found'
      USING errcode = '42501';
  END IF;

  IF membership_role <> 'admin'
    AND case_owner_user_id IS DISTINCT FROM p_requested_by_user_id
    AND item_owner_user_id IS DISTINCT FROM p_requested_by_user_id
  THEN
    RAISE EXCEPTION 'mortgage_case_manager_permission_required'
      USING errcode = '42501';
  END IF;

  IF application_reference IS DISTINCT FROM canonical_application_reference
    OR canonical_application_reference !~ '^OEB-[0-9]{8}-[0-9]{6}$'
  THEN
    RAISE EXCEPTION 'crm_mock_bank_application_reference_invalid_or_tampered'
      USING errcode = '55000';
  END IF;
  application_reference := canonical_application_reference;

  IF NOT EXISTS (
    SELECT 1
    FROM public.mail_connections AS connection
    WHERE connection.organization_id = p_organization_id
      AND connection.owner_user_id = p_requested_by_user_id
      AND connection.id = p_recipient_connection_id
      AND connection.status = 'active'
  ) THEN
    RAISE EXCEPTION 'crm_mock_bank_recipient_connection_not_active'
      USING errcode = '42501';
  END IF;

  SELECT dispatch.*
  INTO dispatch_row
  FROM public.crm_mock_bank_dispatches AS dispatch
  WHERE dispatch.application_id = p_application_id
    AND dispatch.kind = p_kind
  FOR UPDATE;

  IF FOUND AND dispatch_row.status = 'sent' AND NOT p_force_resend THEN
    RETURN private.crm_mock_bank_dispatch_response(
      dispatch_row.id,
      application_reference,
      'sent',
      false
    );
  END IF;

  IF FOUND
    AND dispatch_row.status = 'pending'
    AND dispatch_row.lease_expires_at > lease_now
  THEN
    RETURN private.crm_mock_bank_dispatch_response(
      dispatch_row.id,
      application_reference,
      'in_progress',
      false
    );
  END IF;

  IF (p_kind = 'esis' AND process_stage <> 'pre_application')
    OR (p_kind = 'credit_decision' AND process_stage <> 'under_review')
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_stage_mismatch'
      USING errcode = '23514';
  END IF;

  IF NOT FOUND THEN
    IF p_force_resend THEN
      RAISE EXCEPTION 'crm_mock_bank_force_resend_requires_sent_generation'
        USING errcode = '22023';
    END IF;
    next_dispatch_id := gen_random_uuid();
    next_payload_id := gen_random_uuid();
    INSERT INTO public.crm_mock_bank_dispatches (
      id,
      organization_id,
      case_id,
      application_id,
      kind,
      status,
      generation,
      generation_started_at,
      attempts,
      request_id,
      requested_by_user_id,
      recipient_connection_id,
      payload_id,
      manifest_storage_path,
      archive_storage_path,
      last_attempt_at,
      lease_expires_at,
      created_at,
      updated_at
    ) VALUES (
      next_dispatch_id,
      p_organization_id,
      p_case_id,
      p_application_id,
      p_kind,
      'pending',
      1,
      lease_now,
      1,
      p_request_id,
      p_requested_by_user_id,
      p_recipient_connection_id,
      next_payload_id,
      p_organization_id::text || '/' || p_application_id::text || '/' ||
        next_dispatch_id::text || '/' || p_kind || '/generation-1-' ||
        next_payload_id::text || '.json',
      p_organization_id::text || '/' || p_application_id::text || '/' ||
        next_dispatch_id::text || '/' || p_kind || '/generation-1-' ||
        next_payload_id::text || '.zip',
      lease_now,
      lease_now + interval '5 minutes',
      lease_now,
      lease_now
    )
    RETURNING * INTO dispatch_row;

    RETURN private.crm_mock_bank_dispatch_response(
      dispatch_row.id,
      application_reference,
      'claimed',
      true
    );
  END IF;

  IF dispatch_row.request_id = p_request_id THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_new_request_required'
      USING errcode = '22023';
  END IF;

  IF dispatch_row.status = 'sent' THEN
    IF dispatch_row.sent_at > lease_now - interval '60 seconds' THEN
      RAISE EXCEPTION 'crm_mock_bank_force_resend_cooldown'
        USING errcode = '55000';
    END IF;
    -- An explicit resend is a new business generation with a new payload and
    -- Resend idempotency identity. It may deliberately bind another mailbox.
    next_generation := dispatch_row.generation + 1;
    next_payload_id := gen_random_uuid();
    UPDATE public.crm_mock_bank_dispatches AS dispatch
    SET status = 'pending',
        generation = next_generation,
        generation_started_at = lease_now,
        attempts = 1,
        request_id = p_request_id,
        requested_by_user_id = p_requested_by_user_id,
        recipient_connection_id = p_recipient_connection_id,
        payload_id = next_payload_id,
        manifest_storage_path = p_organization_id::text || '/' ||
          p_application_id::text || '/' || dispatch.id::text || '/' || p_kind ||
          '/generation-' || next_generation::text || '-' || next_payload_id::text || '.json',
        manifest_sha256 = NULL,
        manifest_size_bytes = NULL,
        archive_storage_path = p_organization_id::text || '/' ||
          p_application_id::text || '/' || dispatch.id::text || '/' || p_kind ||
          '/generation-' || next_generation::text || '-' || next_payload_id::text || '.zip',
        archive_sha256 = NULL,
        archive_size_bytes = NULL,
        payload_sha256 = NULL,
        payload_ready_at = NULL,
        provider_message_id = NULL,
        error_code = NULL,
        last_attempt_at = lease_now,
        lease_expires_at = lease_now + interval '5 minutes',
        sent_at = NULL,
        failed_at = NULL,
        updated_at = lease_now
    WHERE dispatch.id = dispatch_row.id
    RETURNING * INTO dispatch_row;
  ELSIF dispatch_row.status = 'failed'
    AND dispatch_row.error_code = 'payload_retention_expired'
  THEN
    IF p_force_resend THEN
      RAISE EXCEPTION 'crm_mock_bank_force_resend_requires_sent_generation'
        USING errcode = '22023';
    END IF;
    -- The prior encrypted bytes were durably deleted after the retention
    -- window. Restart with a fresh business generation and idempotency key;
    -- never recreate different bytes under the expired generation.
    next_generation := dispatch_row.generation + 1;
    next_payload_id := gen_random_uuid();
    UPDATE public.crm_mock_bank_dispatches AS dispatch
    SET status = 'pending',
        generation = next_generation,
        generation_started_at = lease_now,
        attempts = 1,
        request_id = p_request_id,
        requested_by_user_id = p_requested_by_user_id,
        recipient_connection_id = p_recipient_connection_id,
        payload_id = next_payload_id,
        manifest_storage_path = p_organization_id::text || '/' ||
          p_application_id::text || '/' || dispatch.id::text || '/' || p_kind ||
          '/generation-' || next_generation::text || '-' || next_payload_id::text || '.json',
        manifest_sha256 = NULL,
        manifest_size_bytes = NULL,
        archive_storage_path = p_organization_id::text || '/' ||
          p_application_id::text || '/' || dispatch.id::text || '/' || p_kind ||
          '/generation-' || next_generation::text || '-' || next_payload_id::text || '.zip',
        archive_sha256 = NULL,
        archive_size_bytes = NULL,
        payload_sha256 = NULL,
        payload_ready_at = NULL,
        provider_message_id = NULL,
        error_code = NULL,
        last_attempt_at = lease_now,
        lease_expires_at = lease_now + interval '5 minutes',
        sent_at = NULL,
        failed_at = NULL,
        updated_at = lease_now
    WHERE dispatch.id = dispatch_row.id
    RETURNING * INTO dispatch_row;
  ELSE
    IF p_force_resend THEN
      RAISE EXCEPTION 'crm_mock_bank_force_resend_requires_sent_generation'
        USING errcode = '22023';
    END IF;
    IF dispatch_row.recipient_connection_id IS NULL
      OR dispatch_row.recipient_connection_id IS DISTINCT FROM p_recipient_connection_id
      OR dispatch_row.requested_by_user_id IS DISTINCT FROM p_requested_by_user_id
    THEN
      RAISE EXCEPTION 'crm_mock_bank_dispatch_recipient_binding_mismatch'
        USING errcode = '23514';
    END IF;

    -- Retry the same generation. The payload identity, object paths, issue
    -- date and recipient binding remain immutable.
    UPDATE public.crm_mock_bank_dispatches AS dispatch
    SET status = 'pending',
        attempts = dispatch.attempts + 1,
        request_id = p_request_id,
        provider_message_id = NULL,
        error_code = NULL,
        last_attempt_at = lease_now,
        lease_expires_at = lease_now + interval '5 minutes',
        sent_at = NULL,
        failed_at = NULL,
        updated_at = lease_now
    WHERE dispatch.id = dispatch_row.id
    RETURNING * INTO dispatch_row;
  END IF;

  RETURN private.crm_mock_bank_dispatch_response(
    dispatch_row.id,
    application_reference,
    'claimed',
    true
  );
END;
$$;

COMMENT ON FUNCTION public.reserve_crm_mock_bank_dispatch(
  uuid, uuid, uuid, text, uuid, uuid, uuid, boolean
) IS
  'Claims a stage-safe five-minute send lease. Retries preserve the exact generation payload and recipient; force resend after sent creates a new generation.';

CREATE FUNCTION public.commit_crm_mock_bank_dispatch_payload(
  p_dispatch_id uuid,
  p_request_id uuid,
  p_generation integer,
  p_manifest_sha256 text,
  p_manifest_size_bytes integer,
  p_archive_sha256 text,
  p_archive_size_bytes integer,
  p_payload_sha256 text
) RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  dispatch_row public.crm_mock_bank_dispatches%rowtype;
  application_reference text;
  committed_now timestamptz := clock_timestamp();
BEGIN
  IF p_dispatch_id IS NULL
    OR p_request_id IS NULL
    OR p_generation IS NULL
    OR p_generation < 1
    OR p_manifest_sha256 !~ '^[0-9a-f]{64}$'
    OR p_archive_sha256 !~ '^[0-9a-f]{64}$'
    OR p_payload_sha256 !~ '^[0-9a-f]{64}$'
    OR p_manifest_size_bytes NOT BETWEEN 1 AND 5242880
    OR p_archive_size_bytes NOT BETWEEN 1 AND 5242880
  THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_payload_commit'
      USING errcode = '22023';
  END IF;

  SELECT dispatch.*
  INTO dispatch_row
  FROM public.crm_mock_bank_dispatches AS dispatch
  WHERE dispatch.id = p_dispatch_id
  FOR UPDATE;

  IF NOT FOUND
    OR dispatch_row.request_id IS DISTINCT FROM p_request_id
    OR dispatch_row.generation IS DISTINCT FROM p_generation
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_not_found'
      USING errcode = '42501';
  END IF;

  SELECT submission.external_reference
  INTO application_reference
  FROM public.crm_item_submissions AS submission
  WHERE submission.id = dispatch_row.application_id;

  IF dispatch_row.status <> 'pending'
    OR dispatch_row.lease_expires_at <= committed_now
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_expired_or_finalized'
      USING errcode = '40001';
  END IF;

  IF dispatch_row.payload_ready_at IS NOT NULL THEN
    IF dispatch_row.manifest_sha256 IS DISTINCT FROM p_manifest_sha256
      OR dispatch_row.manifest_size_bytes IS DISTINCT FROM p_manifest_size_bytes
      OR dispatch_row.archive_sha256 IS DISTINCT FROM p_archive_sha256
      OR dispatch_row.archive_size_bytes IS DISTINCT FROM p_archive_size_bytes
      OR dispatch_row.payload_sha256 IS DISTINCT FROM p_payload_sha256
    THEN
      RAISE EXCEPTION 'crm_mock_bank_payload_commit_mismatch'
        USING errcode = '23514';
    END IF;
    RETURN private.crm_mock_bank_dispatch_response(
      dispatch_row.id,
      application_reference,
      'claimed',
      true
    );
  END IF;

  UPDATE public.crm_mock_bank_dispatches AS dispatch
  SET manifest_sha256 = p_manifest_sha256,
      manifest_size_bytes = p_manifest_size_bytes,
      archive_sha256 = p_archive_sha256,
      archive_size_bytes = p_archive_size_bytes,
      payload_sha256 = p_payload_sha256,
      payload_ready_at = committed_now,
      updated_at = committed_now
  WHERE dispatch.id = dispatch_row.id
    AND dispatch.request_id = p_request_id
    AND dispatch.generation = p_generation
    AND dispatch.status = 'pending'
  RETURNING * INTO dispatch_row;

  IF dispatch_row.id IS NULL THEN
    RAISE EXCEPTION 'crm_mock_bank_payload_commit_conflict'
      USING errcode = '40001';
  END IF;

  RETURN private.crm_mock_bank_dispatch_response(
    dispatch_row.id,
    application_reference,
    'claimed',
    true
  );
END;
$$;

COMMENT ON FUNCTION public.commit_crm_mock_bank_dispatch_payload(
  uuid, uuid, integer, text, integer, text, integer, text
) IS
  'Binds immutable private manifest/archive checksums and the full provider-payload checksum to the current unexpired generation lease.';

-- Storage/PDF preparation happens before the external email call. Fence that
-- side effect with a fresh lease under the same application/process locks as
-- reservation, so a delayed worker cannot send after the case advanced or
-- after another request reclaimed the generation.
CREATE FUNCTION public.renew_crm_mock_bank_dispatch_send_lease(
  p_dispatch_id uuid,
  p_request_id uuid,
  p_generation integer
) RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  dispatch_scope record;
  dispatch_row public.crm_mock_bank_dispatches%rowtype;
  process_stage text;
  application_reference text;
  canonical_application_reference text;
  renewal_now timestamptz := clock_timestamp();
BEGIN
  IF p_dispatch_id IS NULL
    OR p_request_id IS NULL
    OR p_generation IS NULL
    OR p_generation < 1
  THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_dispatch_lease_renewal'
      USING errcode = '22023';
  END IF;

  SELECT
    dispatch.organization_id,
    dispatch.case_id,
    dispatch.application_id,
    dispatch.kind
  INTO dispatch_scope
  FROM public.crm_mock_bank_dispatches AS dispatch
  WHERE dispatch.id = p_dispatch_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_not_found'
      USING errcode = '42501';
  END IF;

  SELECT
    process.stage,
    submission.external_reference,
    private.crm_mock_bank_application_reference(
      application.submission_id,
      application.created_at
    )
  INTO
    process_stage,
    application_reference,
    canonical_application_reference
  FROM public.crm_case_bank_applications AS application
  JOIN public.mortgage_banks AS bank
    ON bank.id = application.bank_id
   AND bank.is_mock
  JOIN public.crm_item_submissions AS submission
    ON submission.organization_id = application.organization_id
   AND submission.case_item_id = application.case_item_id
   AND submission.id = application.submission_id
  JOIN public.crm_mortgage_application_processes AS process
    ON process.organization_id = application.organization_id
   AND process.case_id = application.case_id
   AND process.application_id = application.submission_id
  WHERE application.organization_id = dispatch_scope.organization_id
    AND application.case_id = dispatch_scope.case_id
    AND application.submission_id = dispatch_scope.application_id
  FOR UPDATE OF application, process;

  IF NOT FOUND
    OR application_reference IS DISTINCT FROM canonical_application_reference
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_scope_changed'
      USING errcode = '40001';
  END IF;

  SELECT dispatch.*
  INTO dispatch_row
  FROM public.crm_mock_bank_dispatches AS dispatch
  WHERE dispatch.id = p_dispatch_id
  FOR UPDATE;

  IF NOT FOUND
    OR dispatch_row.request_id IS DISTINCT FROM p_request_id
    OR dispatch_row.generation IS DISTINCT FROM p_generation
    OR dispatch_row.status <> 'pending'
    OR dispatch_row.payload_ready_at IS NULL
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_not_current_or_prepared'
      USING errcode = '40001';
  END IF;

  IF dispatch_row.organization_id IS DISTINCT FROM dispatch_scope.organization_id
    OR dispatch_row.case_id IS DISTINCT FROM dispatch_scope.case_id
    OR dispatch_row.application_id IS DISTINCT FROM dispatch_scope.application_id
    OR dispatch_row.kind IS DISTINCT FROM dispatch_scope.kind
    OR (dispatch_row.kind = 'esis' AND process_stage <> 'pre_application')
    OR (dispatch_row.kind = 'credit_decision' AND process_stage <> 'under_review')
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_stage_or_scope_changed'
      USING errcode = '40001';
  END IF;

  UPDATE public.crm_mock_bank_dispatches AS dispatch
  SET last_attempt_at = renewal_now,
      lease_expires_at = renewal_now + interval '5 minutes',
      updated_at = renewal_now
  WHERE dispatch.id = dispatch_row.id
    AND dispatch.request_id = p_request_id
    AND dispatch.generation = p_generation
    AND dispatch.status = 'pending'
  RETURNING * INTO dispatch_row;

  IF dispatch_row.id IS NULL THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_renewal_conflict'
      USING errcode = '40001';
  END IF;

  RETURN private.crm_mock_bank_dispatch_response(
    dispatch_row.id,
    canonical_application_reference,
    'claimed',
    true
  );
END;
$$;

COMMENT ON FUNCTION public.renew_crm_mock_bank_dispatch_send_lease(
  uuid, uuid, integer
) IS
  'Fences the external email side effect with a fresh five-minute lease after payload preparation and revalidates the authoritative process stage.';

CREATE FUNCTION public.finalize_crm_mock_bank_dispatch(
  p_dispatch_id uuid,
  p_request_id uuid,
  p_status text,
  p_provider_message_id text DEFAULT NULL,
  p_error_code text DEFAULT NULL
) RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  dispatch_row public.crm_mock_bank_dispatches%rowtype;
  application_reference text;
  normalized_provider_message_id text := nullif(btrim(p_provider_message_id), '');
  normalized_error_code text := nullif(btrim(p_error_code), '');
  completed_now timestamptz := clock_timestamp();
BEGIN
  IF p_dispatch_id IS NULL
    OR p_request_id IS NULL
    OR p_status IS NULL
    OR p_status NOT IN ('sent', 'failed')
    OR (
      p_status = 'sent'
      AND (
        normalized_provider_message_id IS NULL
        OR char_length(normalized_provider_message_id) > 512
        OR normalized_provider_message_id ~ '[[:cntrl:]]'
        OR normalized_error_code IS NOT NULL
      )
    )
    OR (
      p_status = 'failed'
      AND (
        normalized_provider_message_id IS NOT NULL
        OR normalized_error_code IS NULL
        OR char_length(normalized_error_code) > 100
        OR normalized_error_code !~ '^[a-z0-9]+([._-][a-z0-9]+)*$'
      )
    )
  THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_dispatch_completion'
      USING errcode = '22023';
  END IF;

  SELECT dispatch.*
  INTO dispatch_row
  FROM public.crm_mock_bank_dispatches AS dispatch
  WHERE dispatch.id = p_dispatch_id
  FOR UPDATE;

  IF NOT FOUND OR dispatch_row.request_id IS DISTINCT FROM p_request_id THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_not_found'
      USING errcode = '42501';
  END IF;

  SELECT submission.external_reference
  INTO application_reference
  FROM public.crm_item_submissions AS submission
  WHERE submission.id = dispatch_row.application_id;

  IF dispatch_row.status = p_status THEN
    IF (
      p_status = 'sent'
      AND dispatch_row.provider_message_id IS DISTINCT FROM
        normalized_provider_message_id
    ) OR (
      p_status = 'failed'
      AND dispatch_row.error_code IS DISTINCT FROM normalized_error_code
    ) THEN
      RAISE EXCEPTION 'crm_mock_bank_dispatch_completion_mismatch'
        USING errcode = '23514';
    END IF;

    RETURN private.crm_mock_bank_dispatch_response(
      dispatch_row.id,
      application_reference,
      dispatch_row.status,
      false
    );
  END IF;

  IF dispatch_row.status <> 'pending'
    OR dispatch_row.lease_expires_at <= completed_now
    OR (p_status = 'sent' AND dispatch_row.payload_ready_at IS NULL)
  THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_lease_expired_unprepared_or_finalized'
      USING errcode = '40001';
  END IF;

  UPDATE public.crm_mock_bank_dispatches AS dispatch
  SET status = p_status,
      provider_message_id = CASE
        WHEN p_status = 'sent' THEN normalized_provider_message_id
        ELSE NULL
      END,
      error_code = CASE
        WHEN p_status = 'failed' THEN normalized_error_code
        ELSE NULL
      END,
      lease_expires_at = NULL,
      sent_at = CASE WHEN p_status = 'sent' THEN completed_now ELSE NULL END,
      failed_at = CASE WHEN p_status = 'failed' THEN completed_now ELSE NULL END,
      updated_at = completed_now
  WHERE dispatch.id = dispatch_row.id
    AND dispatch.request_id = p_request_id
    AND dispatch.status = 'pending'
  RETURNING * INTO dispatch_row;

  IF dispatch_row.id IS NULL THEN
    RAISE EXCEPTION 'crm_mock_bank_dispatch_completion_conflict'
      USING errcode = '40001';
  END IF;

  RETURN private.crm_mock_bank_dispatch_response(
    dispatch_row.id,
    application_reference,
    dispatch_row.status,
    false
  );
END;
$$;

COMMENT ON FUNCTION public.finalize_crm_mock_bank_dispatch(
  uuid, uuid, text, text, text
) IS
  'Finalizes only the matching unexpired lease; sent requires a committed exact payload, while failed retains it for byte-identical retry.';

-- Private payload cleanup is durable. A sent transition or dispatch deletion
-- creates one job per object. API actions process jobs immediately on a
-- best-effort basis, while stale locks remain reclaimable by later actions.
CREATE TABLE public.crm_mock_bank_payload_cleanup_jobs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id uuid NOT NULL,
  dispatch_id uuid NOT NULL,
  payload_id uuid NOT NULL,
  generation integer NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  object_kind text NOT NULL,
  object_sha256 text,
  status text DEFAULT 'pending'::text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  available_at timestamptz DEFAULT now() NOT NULL,
  claim_token uuid,
  locked_at timestamptz,
  completed_at timestamptz,
  last_error text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_object_key
    UNIQUE (storage_bucket, storage_path),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_bucket_check CHECK (
    storage_bucket = 'crm-mock-bank-outbox'::text
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_kind_check CHECK (
    object_kind IN ('manifest', 'archive')
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_status_check CHECK (
    status IN ('pending', 'completed')
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_generation_check CHECK (
    generation >= 1
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_attempts_check CHECK (
    attempts >= 0
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_path_check CHECK (
    storage_path LIKE organization_id::text || '/%'
    AND char_length(storage_path) <= 1024
    AND strpos(storage_path, chr(92)) = 0
    AND storage_path NOT LIKE '%//%'
    AND storage_path !~ '(^|/)[.]{1,2}(/|$)'
    AND storage_path !~ '[[:cntrl:]]'
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_hash_check CHECK (
    object_sha256 IS NULL OR object_sha256 ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_lock_check CHECK (
    (claim_token IS NULL AND locked_at IS NULL)
    OR (claim_token IS NOT NULL AND locked_at IS NOT NULL AND status = 'pending')
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_completion_check CHECK (
    (status = 'pending' AND completed_at IS NULL)
    OR (status = 'completed' AND completed_at IS NOT NULL AND claim_token IS NULL AND locked_at IS NULL)
  ),
  CONSTRAINT crm_mock_bank_payload_cleanup_jobs_error_check CHECK (
    last_error IS NULL OR (
      char_length(last_error) <= 100
      AND last_error ~ '^[a-z0-9]+([._-][a-z0-9]+)*$'
    )
  )
);

COMMENT ON TABLE public.crm_mock_bank_payload_cleanup_jobs IS
  'PII-free durable deletion queue for private mock-bank message manifests and encrypted archives.';

CREATE INDEX crm_mock_bank_payload_cleanup_jobs_ready_idx
  ON public.crm_mock_bank_payload_cleanup_jobs (available_at, created_at, id)
  WHERE status = 'pending';

CREATE TRIGGER crm_mock_bank_payload_cleanup_jobs_set_updated_at
  BEFORE UPDATE ON public.crm_mock_bank_payload_cleanup_jobs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE FUNCTION private.enqueue_crm_mock_bank_payload_cleanup()
RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
BEGIN
  IF TG_OP = 'UPDATE'
    AND NOT (NEW.status = 'sent' AND OLD.status IS DISTINCT FROM 'sent')
  THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.crm_mock_bank_payload_cleanup_jobs (
    organization_id,
    dispatch_id,
    payload_id,
    generation,
    storage_bucket,
    storage_path,
    object_kind,
    object_sha256,
    available_at
  ) VALUES
    (
      OLD.organization_id,
      OLD.id,
      OLD.payload_id,
      OLD.generation,
      OLD.manifest_storage_bucket,
      OLD.manifest_storage_path,
      'manifest',
      OLD.manifest_sha256,
      clock_timestamp()
    ),
    (
      OLD.organization_id,
      OLD.id,
      OLD.payload_id,
      OLD.generation,
      OLD.archive_storage_bucket,
      OLD.archive_storage_path,
      'archive',
      OLD.archive_sha256,
      clock_timestamp()
    )
  ON CONFLICT (storage_bucket, storage_path) DO NOTHING;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.enqueue_crm_mock_bank_payload_cleanup()
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE TRIGGER crm_mock_bank_dispatches_enqueue_sent_payload_cleanup
  AFTER UPDATE OF status ON public.crm_mock_bank_dispatches
  FOR EACH ROW
  WHEN (NEW.status = 'sent'::text AND OLD.status IS DISTINCT FROM 'sent'::text)
  EXECUTE FUNCTION private.enqueue_crm_mock_bank_payload_cleanup();

CREATE TRIGGER crm_mock_bank_dispatches_enqueue_deleted_payload_cleanup
  BEFORE DELETE ON public.crm_mock_bank_dispatches
  FOR EACH ROW
  EXECUTE FUNCTION private.enqueue_crm_mock_bank_payload_cleanup();

CREATE FUNCTION private.expire_crm_mock_bank_payloads(
  p_limit integer
) RETURNS integer
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  dispatch_row public.crm_mock_bank_dispatches%rowtype;
  sweep_now timestamptz := clock_timestamp();
  expired_count integer := 0;
BEGIN
  FOR dispatch_row IN
    SELECT dispatch.*
    FROM public.crm_mock_bank_dispatches AS dispatch
    WHERE dispatch.last_attempt_at <= sweep_now - interval '7 days'
      AND dispatch.error_code IS DISTINCT FROM 'payload_retention_expired'
      AND (
        dispatch.status = 'failed'
        OR (
          dispatch.status = 'pending'
          AND dispatch.lease_expires_at <= sweep_now
        )
      )
    ORDER BY dispatch.last_attempt_at, dispatch.id
    FOR UPDATE SKIP LOCKED
    LIMIT p_limit
  LOOP
    INSERT INTO public.crm_mock_bank_payload_cleanup_jobs (
      organization_id,
      dispatch_id,
      payload_id,
      generation,
      storage_bucket,
      storage_path,
      object_kind,
      object_sha256,
      available_at
    ) VALUES
      (
        dispatch_row.organization_id,
        dispatch_row.id,
        dispatch_row.payload_id,
        dispatch_row.generation,
        dispatch_row.manifest_storage_bucket,
        dispatch_row.manifest_storage_path,
        'manifest',
        dispatch_row.manifest_sha256,
        sweep_now
      ),
      (
        dispatch_row.organization_id,
        dispatch_row.id,
        dispatch_row.payload_id,
        dispatch_row.generation,
        dispatch_row.archive_storage_bucket,
        dispatch_row.archive_storage_path,
        'archive',
        dispatch_row.archive_sha256,
        sweep_now
      )
    ON CONFLICT (storage_bucket, storage_path) DO NOTHING;

    UPDATE public.crm_mock_bank_dispatches AS dispatch
    SET status = 'failed',
        manifest_sha256 = NULL,
        manifest_size_bytes = NULL,
        archive_sha256 = NULL,
        archive_size_bytes = NULL,
        payload_sha256 = NULL,
        payload_ready_at = NULL,
        provider_message_id = NULL,
        error_code = 'payload_retention_expired',
        lease_expires_at = NULL,
        sent_at = NULL,
        failed_at = sweep_now,
        updated_at = sweep_now
    WHERE dispatch.id = dispatch_row.id;

    expired_count := expired_count + 1;
  END LOOP;

  RETURN expired_count;
END;
$$;

COMMENT ON FUNCTION private.expire_crm_mock_bank_payloads(integer) IS
  'Queues and forgets private payload bytes for failed or abandoned deliveries after seven days; the next retry must start a new generation.';

REVOKE ALL ON FUNCTION private.expire_crm_mock_bank_payloads(integer)
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE FUNCTION public.claim_crm_mock_bank_payload_cleanup_jobs(
  p_limit integer DEFAULT 4
) RETURNS jsonb
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  claimed jsonb;
  claim_now timestamptz := clock_timestamp();
BEGIN
  IF p_limit IS NULL OR p_limit < 1 OR p_limit > 20 THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_cleanup_limit'
      USING errcode = '22023';
  END IF;

  PERFORM private.expire_crm_mock_bank_payloads(p_limit);

  WITH selected AS (
    SELECT job.id
    FROM public.crm_mock_bank_payload_cleanup_jobs AS job
    WHERE job.status = 'pending'
      AND job.available_at <= claim_now
      AND (job.locked_at IS NULL OR job.locked_at <= claim_now - interval '5 minutes')
    ORDER BY job.available_at, job.created_at, job.id
    FOR UPDATE SKIP LOCKED
    LIMIT p_limit
  ), updated AS (
    UPDATE public.crm_mock_bank_payload_cleanup_jobs AS job
    SET claim_token = gen_random_uuid(),
        locked_at = claim_now,
        attempts = job.attempts + 1,
        last_error = NULL,
        updated_at = claim_now
    FROM selected
    WHERE job.id = selected.id
    RETURNING job.*
  )
  SELECT coalesce(
    jsonb_agg(
      jsonb_build_object(
        'jobId', updated.id,
        'claimToken', updated.claim_token,
        'storageBucket', updated.storage_bucket,
        'storagePath', updated.storage_path,
        'objectSha256', updated.object_sha256,
        'attempts', updated.attempts
      ) ORDER BY updated.created_at, updated.id
    ),
    '[]'::jsonb
  )
  INTO claimed
  FROM updated;

  RETURN claimed;
END;
$$;

CREATE FUNCTION public.finalize_crm_mock_bank_payload_cleanup_job(
  p_job_id uuid,
  p_claim_token uuid,
  p_succeeded boolean,
  p_error_code text DEFAULT NULL
) RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  normalized_error text := nullif(btrim(p_error_code), '');
  completed_now timestamptz := clock_timestamp();
BEGIN
  IF p_job_id IS NULL
    OR p_claim_token IS NULL
    OR p_succeeded IS NULL
    OR (p_succeeded AND normalized_error IS NOT NULL)
    OR (
      NOT p_succeeded
      AND (
        normalized_error IS NULL
        OR char_length(normalized_error) > 100
        OR normalized_error !~ '^[a-z0-9]+([._-][a-z0-9]+)*$'
      )
    )
  THEN
    RAISE EXCEPTION 'invalid_crm_mock_bank_cleanup_completion'
      USING errcode = '22023';
  END IF;

  UPDATE public.crm_mock_bank_payload_cleanup_jobs AS job
  SET status = CASE WHEN p_succeeded THEN 'completed' ELSE 'pending' END,
      claim_token = NULL,
      locked_at = NULL,
      completed_at = CASE WHEN p_succeeded THEN completed_now ELSE NULL END,
      available_at = CASE
        WHEN p_succeeded THEN job.available_at
        ELSE completed_now + make_interval(secs => least(3600, 15 * (2 ^ least(job.attempts, 8))))
      END,
      last_error = normalized_error,
      updated_at = completed_now
  WHERE job.id = p_job_id
    AND job.status = 'pending'
    AND job.claim_token = p_claim_token;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'crm_mock_bank_cleanup_claim_not_found'
      USING errcode = '42501';
  END IF;
END;
$$;

-- Delivery activity is part of the same database transaction as the sent
-- transition, avoiding the gap where the provider accepted mail but the
-- secondary application-side insert failed.
ALTER TABLE public.crm_activities
  ADD COLUMN mock_bank_dispatch_id uuid,
  ADD COLUMN mock_bank_dispatch_generation integer;

ALTER TABLE public.crm_activities
  ADD CONSTRAINT crm_activities_mock_bank_dispatch_shape_check CHECK (
    (mock_bank_dispatch_id IS NULL AND mock_bank_dispatch_generation IS NULL)
    OR (
      mock_bank_dispatch_id IS NOT NULL
      AND mock_bank_dispatch_generation >= 1
      AND activity_type IN (
        'mock_bank_esis_email_accepted',
        'mock_bank_credit_decision_email_accepted'
      )
    )
  );

CREATE UNIQUE INDEX crm_activities_mock_bank_dispatch_generation_key
  ON public.crm_activities (
    organization_id,
    mock_bank_dispatch_id,
    mock_bank_dispatch_generation
  )
  WHERE mock_bank_dispatch_id IS NOT NULL;

COMMENT ON COLUMN public.crm_activities.mock_bank_dispatch_id IS
  'Opaque durable source for an atomically recorded mock-bank delivery activity.';

-- Keep synthetic delivery audit events database-owned just like the generic
-- `email_sent` events introduced in 0057. Without extending those policies,
-- an authenticated member could forge a look-alike row with a NULL dispatch
-- id or mutate/delete a real trigger-created event.
DROP POLICY "organization members can create crm activities"
  ON public.crm_activities;
CREATE POLICY "organization members can create crm activities"
  ON public.crm_activities
  FOR INSERT TO authenticated
  WITH CHECK (
    private.is_organization_member(organization_id)
    AND task_id IS NULL
    AND mail_send_request_id IS NULL
    AND mock_bank_dispatch_id IS NULL
    AND mock_bank_dispatch_generation IS NULL
    AND activity_type NOT IN (
      'email_sent'::text,
      'mock_bank_esis_email_accepted'::text,
      'mock_bank_credit_decision_email_accepted'::text
    )
  );

DROP POLICY "organization members can update non audit activities"
  ON public.crm_activities;
CREATE POLICY "organization members can update non audit activities"
  ON public.crm_activities
  FOR UPDATE TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND task_id IS NULL
    AND mail_send_request_id IS NULL
    AND mock_bank_dispatch_id IS NULL
  )
  WITH CHECK (
    private.is_organization_member(organization_id)
    AND task_id IS NULL
    AND mail_send_request_id IS NULL
    AND mock_bank_dispatch_id IS NULL
    AND mock_bank_dispatch_generation IS NULL
    AND activity_type NOT IN (
      'email_sent'::text,
      'mock_bank_esis_email_accepted'::text,
      'mock_bank_credit_decision_email_accepted'::text
    )
  );

DROP POLICY "organization members can delete non audit activities"
  ON public.crm_activities;
CREATE POLICY "organization members can delete non audit activities"
  ON public.crm_activities
  FOR DELETE TO authenticated
  USING (
    private.is_organization_member(organization_id)
    AND task_id IS NULL
    AND mail_send_request_id IS NULL
    AND mock_bank_dispatch_id IS NULL
  );

CREATE FUNCTION private.record_crm_mock_bank_dispatch_activity()
RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $$
DECLARE
  target_case_item_id uuid;
  target_client_id uuid;
  application_reference text;
BEGIN
  SELECT
    application.case_item_id,
    coalesce(
      (
        SELECT party.client_id
        FROM public.crm_mortgage_application_parties AS party
        WHERE party.organization_id = NEW.organization_id
          AND party.case_id = NEW.case_id
          AND party.application_id = NEW.application_id
        ORDER BY (party.role = 'primary_applicant') DESC, party.created_at, party.client_id
        LIMIT 1
      ),
      crm_case.client_id
    ),
    submission.external_reference
  INTO target_case_item_id, target_client_id, application_reference
  FROM public.crm_case_bank_applications AS application
  JOIN public.crm_cases AS crm_case
    ON crm_case.organization_id = application.organization_id
   AND crm_case.id = application.case_id
  JOIN public.crm_item_submissions AS submission
    ON submission.organization_id = application.organization_id
   AND submission.case_item_id = application.case_item_id
   AND submission.id = application.submission_id
  WHERE application.organization_id = NEW.organization_id
    AND application.case_id = NEW.case_id
    AND application.submission_id = NEW.application_id;

  INSERT INTO public.crm_activities (
    organization_id,
    actor_user_id,
    client_id,
    case_id,
    case_item_id,
    submission_id,
    activity_type,
    title,
    body,
    payload,
    created_at,
    mock_bank_dispatch_id,
    mock_bank_dispatch_generation
  ) VALUES (
    NEW.organization_id,
    NEW.requested_by_user_id,
    target_client_id,
    NEW.case_id,
    target_case_item_id,
    NEW.application_id,
    CASE
      WHEN NEW.kind = 'esis' THEN 'mock_bank_esis_email_accepted'
      ELSE 'mock_bank_credit_decision_email_accepted'
    END,
    CASE
      WHEN NEW.kind = 'esis' THEN 'Dostawca poczty przyjął formularz ESIS do wysyłki'
      ELSE 'Dostawca poczty przyjął decyzję kredytową do wysyłki'
    END,
    'Dostawca przyjął wiadomość z PDF w archiwum ZIP zabezpieczonym numerem PESEL głównego wnioskodawcy. Ten wpis nie potwierdza doręczenia do skrzynki.',
    jsonb_build_object(
      'applicationId', NEW.application_id,
      'applicationNumber', application_reference,
      'documentKind', NEW.kind,
      'generation', NEW.generation,
      'providerMessageId', NEW.provider_message_id
    ),
    NEW.sent_at,
    NEW.id,
    NEW.generation
  )
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.record_crm_mock_bank_dispatch_activity()
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

CREATE TRIGGER crm_mock_bank_dispatches_record_sent_activity
  AFTER UPDATE OF status ON public.crm_mock_bank_dispatches
  FOR EACH ROW
  WHEN (NEW.status = 'sent'::text AND OLD.status IS DISTINCT FROM 'sent'::text)
  EXECUTE FUNCTION private.record_crm_mock_bank_dispatch_activity();

ALTER TABLE public.crm_mock_bank_dispatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_mock_bank_payload_cleanup_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY crm_mock_bank_dispatches_service_all
  ON public.crm_mock_bank_dispatches
  FOR ALL TO openexpert_service
  USING (true)
  WITH CHECK (true);

CREATE POLICY crm_mock_bank_payload_cleanup_jobs_service_all
  ON public.crm_mock_bank_payload_cleanup_jobs
  FOR ALL TO openexpert_service
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON TABLE public.crm_mock_bank_dispatches
  FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON TABLE public.crm_mock_bank_payload_cleanup_jobs
  FROM PUBLIC, anonymous, authenticated, openexpert_service;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE public.crm_mock_bank_dispatches
  TO openexpert_service;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE public.crm_mock_bank_payload_cleanup_jobs
  TO openexpert_service;

REVOKE ALL ON FUNCTION public.reserve_crm_mock_bank_dispatch(
  uuid, uuid, uuid, text, uuid, uuid, uuid, boolean
) FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON FUNCTION public.commit_crm_mock_bank_dispatch_payload(
  uuid, uuid, integer, text, integer, text, integer, text
) FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON FUNCTION public.renew_crm_mock_bank_dispatch_send_lease(
  uuid, uuid, integer
) FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON FUNCTION public.finalize_crm_mock_bank_dispatch(
  uuid, uuid, text, text, text
) FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON FUNCTION public.claim_crm_mock_bank_payload_cleanup_jobs(integer)
  FROM PUBLIC, anonymous, authenticated, openexpert_service;
REVOKE ALL ON FUNCTION public.finalize_crm_mock_bank_payload_cleanup_job(
  uuid, uuid, boolean, text
) FROM PUBLIC, anonymous, authenticated, openexpert_service;

GRANT EXECUTE ON FUNCTION public.reserve_crm_mock_bank_dispatch(
  uuid, uuid, uuid, text, uuid, uuid, uuid, boolean
) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.commit_crm_mock_bank_dispatch_payload(
  uuid, uuid, integer, text, integer, text, integer, text
) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.renew_crm_mock_bank_dispatch_send_lease(
  uuid, uuid, integer
) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.finalize_crm_mock_bank_dispatch(
  uuid, uuid, text, text, text
) TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.claim_crm_mock_bank_payload_cleanup_jobs(integer)
  TO openexpert_service;
GRANT EXECUTE ON FUNCTION public.finalize_crm_mock_bank_payload_cleanup_job(
  uuid, uuid, boolean, text
) TO openexpert_service;
