packages:
  - "apps/*"
  - "apps/crm/services/*"
  - "multiform-agent"
  - "packages/*"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

patchedDependencies:
  nitro@3.0.260610-beta: patches/nitro@3.0.260610-beta.patch
