/**
 * Bank Pekao S.A. mortgage-package audit, checked against public Bank Pekao
 * sources on 2026-08-09.
 *
 * This file stays bank-specific and is the audited source of truth consumed
 * by the Pekao runtime templates and the product checklist.
 */

export const PEKAO_COMPLETE_PACKAGE_CHECKED_AT = '2026-08-09' as const

export const PEKAO_OFFICIAL_SOURCE_PAGES = {
  downloads: 'https://www.pekao.com.pl/o-banku/stopka/cennik-i-regulamin.html',
  mortgage: 'https://www.pekao.com.pl/klient-indywidualny/wlasne-mieszkanie-lub-dom/kredyt-hipoteczny.html',
  constructionMortgage: 'https://www.pekao.com.pl/klient-indywidualny/wlasne-mieszkanie-lub-dom/kredyt-budowlano-hipoteczny.html',
  familyMortgage: 'https://www.pekao.com.pl/klient-indywidualny/wlasne-mieszkanie-lub-dom/kredyt-bez-wkladu-wlasnego.html',
  ecoMortgage: 'https://www.pekao.com.pl/klient-indywidualny/wlasne-mieszkanie-lub-dom/eko-kredyt.html',
  documentGuide: 'https://www.pekao.com.pl/poradnik-kredytowy/jakich-dokumentow-potrzebujesz-aby-ubiegac-sie-o-kredyt-hipoteczny.html',
  refinanceGuide: 'https://www.pekao.com.pl/poradnik-kredytowy/przeniesienie-kredytu-hipotecznego-do-innego-banku.html',
  existingMortgage: 'https://www.pekao.com.pl/klient-indywidualny/wlasne-mieszkanie-lub-dom/mam-juz-kredyt.html',
  onlineDispositions: 'https://www.pekao.com.pl/klient-indywidualny/bankowosc-elektroniczna/dyspozycje-i-zaswiadczenia-online.html',
} as const

export type PekaoPackageFillMethod =
  | 'pdf_acroform'
  | 'pdf_manual'
  | 'pdf_readonly'
  | 'xlsx_native'
  | 'xlsx_manual'

export type PekaoPackageScope =
  | 'case'
  | 'each_applicant'
  | 'each_income_source'
  | 'each_disbursement'
  | 'reference'

export type PekaoRequirementMode = 'always' | 'conditional' | 'bank_requested'

export interface PekaoOfficialPackageDocument {
  code: string
  title: string
  category:
    | 'application'
    | 'applicant_information'
    | 'income_form'
    | 'legal_information'
    | 'property_form'
    | 'disbursement'
    | 'product_information'
    | 'reference'
  fillMethod: PekaoPackageFillMethod
  scope: PekaoPackageScope
  requirement: PekaoRequirementMode
  stage: 'application' | 'income' | 'property' | 'information_delivery' | 'disbursement'
  applicability: string
  fileName: string
  mimeType: 'application/pdf' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  sha256: string
  pageCount: number | null
  acroFormFieldCount: number | null
  publishedOrModifiedDate: string
  internalVersion: string | null
  sourcePageUrl: string
  downloadUrl: string
  validity: string | null
  signatures: readonly string[]
  canonicalKeys: readonly string[]
  notes: readonly string[]
}

const downloads = PEKAO_OFFICIAL_SOURCE_PAGES.downloads

export const PEKAO_COMPLETE_PACKAGE_DOCUMENTS = [
  {
    code: 'pekao_mortgage_application',
    title: 'Wniosek o udzielenie kredytu mieszkaniowego',
    category: 'application',
    fillMethod: 'pdf_acroform',
    scope: 'case',
    requirement: 'always',
    stage: 'application',
    applicability: 'Każdy papierowy wniosek mieszkaniowy lub budowlano-hipoteczny; formularz obsługuje maksymalnie czterech wnioskodawców.',
    fileName: 'pekao-wniosek-o-kredyt-mieszkaniowy-2026-06-02.pdf',
    mimeType: 'application/pdf',
    sha256: '735c8457af4dec79c31ccb702fd3c2b77a5fdb57939781f5476a04fdd667374a',
    pageCount: 6,
    acroFormFieldCount: 279,
    publishedOrModifiedDate: '2026-06-02',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3Ac145c931-4923-4868-9b11-1a00de19ecf6/Wniosek-o-udzielenie-kredytu-mieszkaniowego.pdf',
    validity: null,
    signatures: [
      'Każdy aktywny wnioskodawca podpisuje wniosek.',
      'Numer wniosku, jednostkę Banku oraz dane i podpis osoby przyjmującej uzupełnia Bank/Agent/Partner Sprzedaży.',
    ],
    canonicalKeys: [
      'applicants.*.firstName',
      'applicants.*.lastName',
      'applicants.*.targetPropertyOwner',
      'applicants.*.sharedHouseholdWithApplicantNumber',
      'loan.*',
      'investment.*',
      'property.*',
      'collateralProperty.*',
      'households.*',
      'liabilities.*',
      'mortgageDischarges.*',
      'declarations.*',
      'application.place',
      'application.date',
    ],
    notes: [
      'Publiczny plik z 2026-06-02 zastąpił źródło z 2025-02-04 używane przez istniejący template.',
      'Aktualny PDF usunął osiem pól starej wersji: C42-C44, C85-C86 i C103-C105.',
    ],
  },
  {
    code: 'pekao_applicant_information_card',
    title: 'Karta Informacyjna Wnioskodawcy',
    category: 'applicant_information',
    fillMethod: 'pdf_manual',
    scope: 'each_applicant',
    requirement: 'always',
    stage: 'application',
    applicability: 'Oddzielny egzemplarz dla każdego wnioskodawcy.',
    fileName: 'pekao-karta-informacyjna-wnioskodawcy-2026-06.pdf',
    mimeType: 'application/pdf',
    sha256: '7106470a7594728b08275d66f284edcb602656ec65e44a6e123c266ba74ee43e',
    pageCount: 8,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-06-01',
    internalVersion: '2026_06',
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A445d3a4e-5be7-4c08-9594-4c4ca6b50498/Karta-Informacyjna-wnioskodawcy.pdf',
    validity: 'Upoważnienia do BIG InfoMonitor i KRD wskazane w formularzu obowiązują nie dłużej niż 60 dni od podpisania.',
    signatures: [
      'Wnioskodawca podpisuje kartę i wymagane oświadczenia/upoważnienia.',
      'Pracownik Banku/Agent/Partner Sprzedaży potwierdza tożsamość wnioskodawcy.',
    ],
    canonicalKeys: [
      'applicants.*.firstName',
      'applicants.*.middleName',
      'applicants.*.lastName',
      'applicants.*.pesel',
      'applicants.*.birthPlace',
      'applicants.*.identityDocumentType',
      'applicants.*.identityDocumentNumber',
      'applicants.*.citizenship',
      'applicants.*.phone',
      'applicants.*.email',
      'applicants.*.residentialAddress',
      'applicants.*.correspondenceAddress',
      'applicants.*.maritalStatus',
      'applicants.*.maritalPropertyCommunity',
      'applicants.*.housingStatus',
      'applicants.*.education',
      'applicants.*.occupation',
      'applicants.*.incomeSource',
      'applicants.*.monthlyMaintenanceCosts',
      'applicants.*.alimonyAndLegalBurdens',
      'applicants.*.liabilities.*',
    ],
    notes: [
      'Przypis nr 3 wymaga dodatkowego oświadczenia bankowego od wnioskodawcy prowadzącego działalność lub posiadającego udziały.',
      'Przypis nr 4 wymaga Oświadczenia o zatrudnieniu dla pracy w kraju, umowy cywilnoprawnej i zatrudnienia/kontraktu za granicą.',
    ],
  },
  {
    code: 'pekao_employer_income_certificate',
    title: 'Zaświadczenie o zatrudnieniu',
    category: 'income_form',
    fillMethod: 'pdf_manual',
    scope: 'each_income_source',
    requirement: 'conditional',
    stage: 'income',
    applicability: 'Każda wykazywana umowa o pracę, umowa cywilnoprawna lub praca/kontrakt za granicą, gdy dochód potwierdza pracodawca albo zleceniodawca.',
    fileName: 'pekao-zaswiadczenie-o-zatrudnieniu-2026-07-07.pdf',
    mimeType: 'application/pdf',
    sha256: '876c4c205a35b89eefd1ea797dc945405be19246d76e38799624f8f347abf56c',
    pageCount: 2,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-07',
    internalVersion: null,
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A4d9077b8-b015-4b3b-96a2-d1ab9f31671c/Zaswiadczenie_o_zatrudnieniu.pdf',
    validity: 'Jeden miesiąc od daty wystawienia.',
    signatures: [
      'Pracodawca/zleceniodawca podaje dane firmy oraz składa podpis; formularz przewiduje stempel firmowy/REGON.',
      'Pracownik Banku/Agent/Partner Sprzedaży podpisuje i stempluje dokument.',
    ],
    canonicalKeys: [
      'applicants.*.firstName',
      'applicants.*.lastName',
      'applicants.*.pesel',
      'applicants.*.employerName',
      'applicants.*.employerRegon',
      'applicants.*.employerAddress',
      'applicants.*.employmentBenefitType',
      'applicants.*.employmentStartDate',
      'applicants.*.employmentContractDuration',
      'applicants.*.employmentEndDate',
      'applicants.*.jobTitle',
      'applicants.*.averageNetIncome',
      'applicants.*.incomeCurrency',
      'applicants.*.salaryPaymentMethod',
      'applicants.*.salaryGarnished',
      'applicants.*.salaryGarnishmentAmount',
    ],
    notes: ['Każda równoległa umowa stanowi osobne źródło dochodu i wymaga osobnego wprowadzenia.'],
  },
  {
    code: 'pekao_applicant_employment_statement',
    title: 'Oświadczenie o zatrudnieniu',
    category: 'income_form',
    fillMethod: 'pdf_manual',
    scope: 'each_income_source',
    requirement: 'conditional',
    stage: 'income',
    applicability: 'Wymagane przez przypis nr 4 Karty Informacyjnej dla pracy w kraju, umowy cywilnoprawnej i pracy/kontraktu za granicą.',
    fileName: 'pekao-oswiadczenie-o-zatrudnieniu-2026-07-07.pdf',
    mimeType: 'application/pdf',
    sha256: '7fe4e7e83ad6be084e7c0e54afc2ab00d8edf1d00377b4fb8770577fee161f02',
    pageCount: 2,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-07',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A947f425e-6b55-470b-921b-88e78e96184b/Oswiadczenie_o_zatrudnieniu.pdf',
    validity: 'Jeden miesiąc od daty podpisania przez klienta.',
    signatures: ['Klient podpisuje oświadczenie.', 'Pracownik Banku/Agent/Partner Sprzedaży podpisuje i stempluje dokument.'],
    canonicalKeys: [
      'applicants.*.firstName',
      'applicants.*.lastName',
      'applicants.*.pesel',
      'applicants.*.employerName',
      'applicants.*.employerRegon',
      'applicants.*.employerAddress',
      'applicants.*.employmentBenefitType',
      'applicants.*.employmentStartDate',
      'applicants.*.employmentContractDuration',
      'applicants.*.employmentEndDate',
      'applicants.*.jobTitle',
      'applicants.*.occupation',
      'applicants.*.averageNetIncome',
      'applicants.*.incomeCurrency',
      'applicants.*.salaryPaymentMethod',
      'applicants.*.salaryGarnished',
      'applicants.*.salaryGarnishmentAmount',
    ],
    notes: ['Każda równoległa umowa stanowi osobne źródło dochodu i wymaga osobnego oświadczenia.'],
  },
  {
    code: 'pekao_business_statement_unchanged_taxation',
    title: 'Oświadczenie o prowadzonej działalności — bez zmiany formy opodatkowania',
    category: 'income_form',
    fillMethod: 'pdf_manual',
    scope: 'each_applicant',
    requirement: 'conditional',
    stage: 'income',
    applicability: 'Wnioskodawca prowadzący działalność, który w ostatnich 12 miesiącach nie zmienił formy opodatkowania.',
    fileName: 'pekao-oswiadczenie-o-prowadzonej-dzialalnosci-2026-07-10.pdf',
    mimeType: 'application/pdf',
    sha256: '8809c84bd8ff6d8eb4ba9933e0921bb62eee4d5c44c4a6799cbb3cb1ca07a836',
    pageCount: 6,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-10',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A8f15aeef-b475-4f09-a259-9fe8c9de31b4/Oswiadczenie_o_prowadzonej_dzialalnosci_v2.pdf',
    validity: 'Jeden miesiąc od daty podpisania przez klienta.',
    signatures: ['Klient podpisuje oświadczenie.', 'Pracownik Banku/Agent/Partner Sprzedaży podpisuje i stempluje dokument.'],
    canonicalKeys: ['applicants.*.businessLegalForm', 'applicants.*.pkdCode', 'pekao.business.*'],
    notes: ['Nie stosować, jeżeli forma opodatkowania zmieniła się w ostatnich 12 miesiącach.'],
  },
  {
    code: 'pekao_business_statement_changed_taxation',
    title: 'Oświadczenie o prowadzonej działalności — zmiana formy opodatkowania w ostatnich 12 miesiącach',
    category: 'income_form',
    fillMethod: 'pdf_manual',
    scope: 'each_applicant',
    requirement: 'conditional',
    stage: 'income',
    applicability: 'Wnioskodawca prowadzący działalność, który w ostatnich 12 miesiącach zmienił formę opodatkowania.',
    fileName: 'pekao-oswiadczenie-dzialalnosc-zmiana-opodatkowania-2026-07-10.pdf',
    mimeType: 'application/pdf',
    sha256: '64d3131442bb93d11d18a00f8b918270037060243574f71f72ecac4ba45df75a',
    pageCount: 7,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-10',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3Aebea0338-c9a7-4df3-aa9b-34edecf71baa/Oswiadczenie_o_prowadzonej_dzialalnosci_zmiana_opodatkowania_12_m-cy_v2.pdf',
    validity: 'Jeden miesiąc od daty podpisania przez klienta.',
    signatures: ['Klient podpisuje oświadczenie.', 'Pracownik Banku/Agent/Partner Sprzedaży podpisuje i stempluje dokument.'],
    canonicalKeys: ['applicants.*.businessLegalForm', 'applicants.*.pkdCode', 'pekao.business.*', 'pekao.business.taxationChange.*'],
    notes: ['Wariant rozłączny z formularzem bez zmiany opodatkowania.'],
  },
  {
    code: 'pekao_related_company_or_farm_statement',
    title: 'Oświadczenie o spółce powiązanej lub gospodarstwie rolnym',
    category: 'income_form',
    fillMethod: 'pdf_manual',
    scope: 'each_applicant',
    requirement: 'conditional',
    stage: 'income',
    applicability: 'Wnioskodawca posiadający co najmniej 20% udziałów w spółce albo będący właścicielem/współwłaścicielem gospodarstwa rolnego.',
    fileName: 'pekao-oswiadczenie-spolka-lub-gospodarstwo-2026-07-07.pdf',
    mimeType: 'application/pdf',
    sha256: '420c971213a186d71e4bf8e469487fa1052171ec5fef144ba4b89052fd058ff9',
    pageCount: 2,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-07',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A09aa8f39-b182-414e-945e-ce3eead78be4/Oswiadczenie_o_spolce_powiazanej_gosp_rolnym.pdf',
    validity: 'Jeden miesiąc od daty podpisania przez klienta.',
    signatures: ['Klient podpisuje oświadczenie.', 'Pracownik Banku/Agent/Partner Sprzedaży podpisuje i stempluje dokument.'],
    canonicalKeys: ['pekao.relatedCompany.*', 'pekao.agriculturalBusiness.*'],
    notes: [],
  },
  {
    code: 'pekao_personal_data_information_iad',
    title: 'Informacje dotyczące przetwarzania danych osobowych — Formularz Informacyjny IAD',
    category: 'legal_information',
    fillMethod: 'pdf_manual',
    scope: 'each_applicant',
    requirement: 'always',
    stage: 'information_delivery',
    applicability: 'Oddzielny egzemplarz dla każdego wnioskodawcy.',
    fileName: 'pekao-formularz-iad-2026-07-29.pdf',
    mimeType: 'application/pdf',
    sha256: 'b912179a3cbfd8e618e00775995350a6ff9f79240feb379cebe72938affa34ad',
    pageCount: 3,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-29',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A4568d894-e480-47c6-8f7e-939d7cf7fbb1/Informacje-dotyczace-przetwarzania-danych-osobowych-Formularz-Informacyjny-IAD.pdf',
    validity: null,
    signatures: [
      'Wnioskodawca podpisuje potwierdzenie otrzymania informacji.',
      'Jeżeli wybiera przesłanie na e-mail, składa dodatkowy podpis pod zgodą i podaje adres e-mail.',
    ],
    canonicalKeys: ['applicants.*.firstName', 'applicants.*.lastName', 'applicants.*.email', 'pekao.consents.iadElectronicDelivery'],
    notes: ['Dowód doręczenia należy przechowywać per wnioskodawca; sam plik bez podpisu nie zamyka kroku.'],
  },
  {
    code: 'pekao_agricultural_land_statement',
    title: 'Oświadczenie Wnioskodawcy dotyczące gruntów rolnych',
    category: 'property_form',
    fillMethod: 'pdf_manual',
    scope: 'case',
    requirement: 'conditional',
    stage: 'property',
    applicability: 'Gdy finansowana nieruchomość lub zabezpieczenie obejmuje grunt sklasyfikowany jako rolny.',
    fileName: 'pekao-oswiadczenie-grunty-rolne-2025-10-20.pdf',
    mimeType: 'application/pdf',
    sha256: 'e785ef043f75ab6d59962319e9870c679c31defeb6f4e247c9ee2e48631c4058',
    pageCount: 1,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2025-10-20',
    internalVersion: '2025_10',
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3Ac617fbaa-5a4b-4574-a7e5-7b42dccec7f4/Oswiadczenie-Wnioskodawcy-rolne.pdf',
    validity: null,
    signatures: ['Wnioskodawca składa podpis pod oświadczeniem.'],
    canonicalKeys: ['property.landRegisterNumber', 'property.classification', 'property.agriculturalUse', 'property.agriculturalHoldingArea'],
    notes: [],
  },
  {
    code: 'pekao_disbursement_or_tranche_request',
    title: 'Wniosek o wypłatę kredytu / transzy',
    category: 'disbursement',
    fillMethod: 'pdf_manual',
    scope: 'each_disbursement',
    requirement: 'conditional',
    stage: 'disbursement',
    applicability: 'Po zawarciu umowy, dla jednorazowej wypłaty albo każdej transzy.',
    fileName: 'pekao-wniosek-o-wyplate-transzy-2026-07-24.pdf',
    mimeType: 'application/pdf',
    sha256: '307e8d76cff60d8d299c69cf38cf4c85fdf8eb52fdcfd8d5a40148f307b6dbfd',
    pageCount: 2,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-07-24',
    internalVersion: null,
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.existingMortgage,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A6edfe79b-4308-410f-ab05-a804b53dc402/Wniosek-o-wyp%C5%82ate-kredytu-transzy.pdf',
    validity: null,
    signatures: [
      'Wszyscy współkredytobiorcy podpisują wniosek, chyba że umowa kredytu wyraźnie dopuszcza podpis jednego z nich.',
      'Pracownik Banku potwierdza przyjęcie dokumentu.',
    ],
    canonicalKeys: ['application.date', 'loan.contractNumber', 'loan.disbursementType', 'tranches.*.date', 'tranches.*.amount', 'tranches.*.accountOwner', 'pekao.disbursement.*'],
    notes: ['Spełnienie warunków wypłaty trzeba sprawdzić osobno według zawartej umowy kredytu.'],
  },
  {
    code: 'pekao_general_mortgage_information',
    title: 'Informacje ogólne — mieszkaniowy kredyt hipoteczny',
    category: 'product_information',
    fillMethod: 'pdf_readonly',
    scope: 'case',
    requirement: 'always',
    stage: 'information_delivery',
    applicability: 'Standardowy mieszkaniowy kredyt hipoteczny.',
    fileName: 'pekao-informacje-ogolne-kredyt-hipoteczny-2026-06.pdf',
    mimeType: 'application/pdf',
    sha256: '1d598e3869e306dcd7b94ae9952e861550fdac6651df1686d079d3f0ac22c737',
    pageCount: 16,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-06-01',
    internalVersion: '2026_06',
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.mortgage,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3Aa8684393-b66a-4f04-9a4c-b8dc8b02ad67/Informacje-ogolne-mieszkaniowy-kredyt-hipoteczny.pdf',
    validity: null,
    signatures: [],
    canonicalKeys: [],
    notes: ['Dokument do doręczenia/archiwizacji; nie ma pól klienta i nie wolno oznaczać go jako automatycznie uzupełniony.'],
  },
  {
    code: 'pekao_general_construction_mortgage_information',
    title: 'Informacje ogólne — mieszkaniowy kredyt budowlano-hipoteczny',
    category: 'product_information',
    fillMethod: 'pdf_readonly',
    scope: 'case',
    requirement: 'conditional',
    stage: 'information_delivery',
    applicability: 'Budowa, dokończenie budowy albo inny cel budowlano-hipoteczny.',
    fileName: 'pekao-informacje-ogolne-kredyt-budowlano-hipoteczny-2026-06.pdf',
    mimeType: 'application/pdf',
    sha256: 'd33f21e005cbea27dd1d21ca7d2c6311e346800dc628843eed793f64d54385a2',
    pageCount: 15,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-06-01',
    internalVersion: '2026_06',
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.constructionMortgage,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A61ade350-07da-4bd7-9a78-f9e3fec5b561/Informacje-ogolne-mieszkaniowy-kredyt-budowlano-hipoteczny.pdf',
    validity: null,
    signatures: [],
    canonicalKeys: [],
    notes: ['Dokument tylko do odczytu.'],
  },
  {
    code: 'pekao_general_family_mortgage_information',
    title: 'Informacje ogólne — Rodzinny Kredyt Mieszkaniowy',
    category: 'product_information',
    fillMethod: 'pdf_readonly',
    scope: 'case',
    requirement: 'conditional',
    stage: 'information_delivery',
    applicability: 'Wyłącznie Rodzinny Kredyt Mieszkaniowy / gwarancja BGK.',
    fileName: 'pekao-informacje-ogolne-rodzinny-kredyt-mieszkaniowy-2026-06.pdf',
    mimeType: 'application/pdf',
    sha256: 'efd37f9cc2e0f9f3944451578814b2b3fb30243b2f6467c993a52c11a69acbd5',
    pageCount: 18,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2026-06-01',
    internalVersion: '2026_06',
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.familyMortgage,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A608d0c91-6b16-482f-9198-ebea6e3d8d16/Informacje-ogolne.pdf',
    validity: null,
    signatures: [],
    canonicalKeys: [],
    notes: ['Publiczna strona nie udostępnia osobnego formularza kwalifikacyjnego; kwalifikację trzeba prowadzić jako czynność eksperta.'],
  },
  {
    code: 'pekao_appraiser_guidelines',
    title: 'Wytyczne dla rzeczoznawców majątkowych',
    category: 'reference',
    fillMethod: 'pdf_readonly',
    scope: 'reference',
    requirement: 'conditional',
    stage: 'property',
    applicability: 'Gdy operat przygotowuje rzeczoznawca wybrany przez klienta lub eksperta.',
    fileName: 'pekao-wytyczne-rzeczoznawcy-2024-05-29.pdf',
    mimeType: 'application/pdf',
    sha256: '5c577a22f31196129c009c5f9dc2bb037636befeb7702403d4053617ebaa5955',
    pageCount: 5,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2024-05-29',
    internalVersion: null,
    sourcePageUrl: downloads,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A86bc96f2-4e19-42bb-a04e-16402558624c/Wytyczne%20dla%20rzeczoznawc%C3%B3w%20maj%C4%85tkowych.pdf',
    validity: null,
    signatures: ['Rzeczoznawca podpisuje oświadczenie dotyczące przetwarzania danych, jeżeli ma zastosowanie.'],
    canonicalKeys: [],
    notes: ['Dokument referencyjny opisuje wymagane załączniki do operatu; nie jest formularzem klienta.'],
  },
  {
    code: 'pekao_accepted_insurers',
    title: 'Lista ubezpieczycieli akceptowanych przez Bank',
    category: 'reference',
    fillMethod: 'pdf_readonly',
    scope: 'reference',
    requirement: 'conditional',
    stage: 'property',
    applicability: 'Przy wyborze zewnętrznego ubezpieczenia nieruchomości.',
    fileName: 'pekao-lista-akceptowanych-ubezpieczycieli-2023-12-18.pdf',
    mimeType: 'application/pdf',
    sha256: '05f9389ef5ce886a77410b0cfd92edc9e6dfa203e8845bca21340f370f124402',
    pageCount: 1,
    acroFormFieldCount: 0,
    publishedOrModifiedDate: '2023-12-18',
    internalVersion: null,
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.existingMortgage,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3A24270912-8fb4-4835-a343-bb556ddb7a13/Lista%20ubezpieczycieli%20akceptowanych%20przez%20bank.pdf',
    validity: null,
    signatures: [],
    canonicalKeys: [],
    notes: ['Przed użyciem należy ponownie sprawdzić aktualną listę na stronie Banku.'],
  },
  {
    code: 'pekao_construction_renovation_cost_estimate',
    title: 'Kosztorys budowlano-remontowy',
    category: 'property_form',
    fillMethod: 'xlsx_native',
    scope: 'case',
    requirement: 'conditional',
    stage: 'property',
    applicability: 'Budowa, remont, modernizacja lub wykończenie finansowane kredytem.',
    fileName: 'pekao-kosztorys-budowlano-remontowy-2026-03-05.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    sha256: '0ace4ee3caada4b266e5babb0bdf7959a6af7d662dbe68ca95aeb20716ca6dfb',
    pageCount: null,
    acroFormFieldCount: null,
    publishedOrModifiedDate: '2026-03-05',
    internalVersion: null,
    sourcePageUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    downloadUrl: 'https://www.pekao.com.pl/dam/jcr%3Ac7f707b2-d691-4b24-bc65-b1040754a26e/Kosztorys-budowlano-remontowy.xlsx',
    validity: null,
    signatures: [],
    canonicalKeys: [
      'applicants.0.fullName',
      'property.type',
      'property.usableArea',
      'loan.purpose',
      'property.address.*',
      'loan.amount',
      'property.preWorksValue',
      'investment.completionDate',
      'tranches.*',
    ],
    notes: [
      'Metoda xlsx_native wpisuje dane wspólne i harmonogram transz do zatwierdzonych komórek.',
      'Zachować jako arkusz XLSX; nie konwertować do sztucznego PDF-u.',
      'Szczegółowe pozycje robót ekspert uzupełnia ręcznie.',
    ],
  },
] as const satisfies readonly PekaoOfficialPackageDocument[]

export interface PekaoClientDocumentRequirement {
  code: string
  title: string
  scope: 'case' | 'each_applicant' | 'each_income_source'
  stage: 'income' | 'property' | 'refinance' | 'insurance' | 'disbursement'
  requirement: PekaoRequirementMode
  applicability: string
  validity: string | null
  sourceUrl: string
  evidence: 'official_document_guide' | 'official_product_page' | 'official_form' | 'case_specific_bank_request'
  notes: readonly string[]
}

/**
 * Attachments supplied by the customer or third parties. These are not Bank
 * templates and must never be represented as generated Pekao PDFs.
 */
export const PEKAO_CLIENT_DOCUMENT_REQUIREMENTS = [
  {
    code: 'income_employer_certificate',
    title: 'Zaświadczenie pracodawcy/zleceniodawcy o zatrudnieniu i dochodzie',
    scope: 'each_income_source',
    stage: 'income',
    requirement: 'conditional',
    applicability: 'Dochód z pracy, umowy cywilnoprawnej albo kontraktu zagranicznego.',
    validity: 'Jeden miesiąc od wystawienia.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Użyć aktualnego bankowego zaświadczenia ujętego w katalogu powyżej.'],
  },
  {
    code: 'income_salary_statement_and_pit37',
    title: 'Wyciąg rachunku z wpływami wynagrodzenia i ostatni PIT-37',
    scope: 'each_income_source',
    stage: 'income',
    requirement: 'bank_requested',
    applicability: 'Dochód z zatrudnienia, jeżeli Bank zażąda dodatkowego potwierdzenia.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Publiczny poradnik używa sformułowania „Bank może poprosić”.'],
  },
  {
    code: 'business_zus_and_tax_clearance',
    title: 'Zaświadczenia o niezaleganiu wobec ZUS i urzędu skarbowego',
    scope: 'each_applicant',
    stage: 'income',
    requirement: 'conditional',
    applicability: 'Dochód z działalności gospodarczej.',
    validity: 'Jeden miesiąc od wystawienia.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: [],
  },
  {
    code: 'business_kpir_and_account_statement',
    title: 'Kopia KPiR i wyciąg firmowego rachunku',
    scope: 'each_applicant',
    stage: 'income',
    requirement: 'conditional',
    applicability: 'Działalność rozliczana według skali podatkowej na KPiR.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Dla innych form opodatkowania Bank określa dokumenty indywidualnie.'],
  },
  {
    code: 'pension_or_disability_income',
    title: 'Decyzja/aktualna waloryzacja świadczenia i dowód wpływu',
    scope: 'each_income_source',
    stage: 'income',
    requirement: 'conditional',
    applicability: 'Emerytura albo renta.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Dowodem wpływu może być wyciąg rachunku; Bank może zażądać dalszego dokumentu dochodowego.'],
  },
  {
    code: 'primary_market_transaction_documents',
    title: 'Dokumenty zakupu na rynku pierwotnym',
    scope: 'case',
    stage: 'property',
    requirement: 'conditional',
    applicability: 'Zakup od dewelopera/spółdzielni.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: [
      'Umowa przedwstępna lub rezerwacyjna.',
      'Wypis z centralnego rejestru gruntów i budynków oraz księga wieczysta gruntu.',
      'Pozwolenie na budowę; dla zakończonej inwestycji także pozwolenie na użytkowanie.',
      'Potwierdzenie wkładu własnego, aktualny KRS dewelopera i pełnomocnictwo reprezentanta, jeśli nie wynika z KRS.',
    ],
  },
  {
    code: 'secondary_market_transaction_documents',
    title: 'Dokumenty zakupu na rynku wtórnym',
    scope: 'case',
    stage: 'property',
    requirement: 'conditional',
    applicability: 'Zakup nieruchomości na rynku wtórnym.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Dokument własności sprzedającego, odpis księgi wieczystej i umowa przedwstępna.'],
  },
  {
    code: 'construction_property_documents',
    title: 'Dokumenty budowy domu',
    scope: 'case',
    stage: 'property',
    requirement: 'conditional',
    applicability: 'Budowa albo dokończenie budowy domu.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: [
      'Ostateczne pozwolenie na budowę, akt własności gruntu i księga wieczysta.',
      'Wypis i wyrys z ewidencji gruntów, projekt budowlany, dziennik budowy i umowy z wykonawcami.',
      'Operat szacunkowy zgodny z aktualnymi wytycznymi Banku.',
    ],
  },
  {
    code: 'renovation_or_finish_documents',
    title: 'Kosztorys i zdjęcia postępu prac',
    scope: 'case',
    stage: 'property',
    requirement: 'conditional',
    applicability: 'Remont, modernizacja lub wykończenie.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.documentGuide,
    evidence: 'official_document_guide',
    notes: ['Kosztorys prowadzić w oficjalnym arkuszu XLSX Pekao.'],
  },
  {
    code: 'eco_energy_evidence',
    title: 'Dokument potwierdzający parametr EP dla EKO Kredytu',
    scope: 'case',
    stage: 'property',
    requirement: 'conditional',
    applicability: 'EKO Kredyt: EP nie wyższy niż 63 kWh/(m²·rok) dla domu lub 58,50 kWh/(m²·rok) dla lokalu.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.ecoMortgage,
    evidence: 'official_product_page',
    notes: [
      'Rynek wtórny: świadectwo charakterystyki energetycznej.',
      'Budowa/rynek pierwotny: projektowana charakterystyka energetyczna albo oświadczenie dewelopera wskazane przez Bank.',
    ],
  },
  {
    code: 'refinanced_loan_closing_documents',
    title: 'Dokumenty zamknięcia refinansowanego kredytu',
    scope: 'case',
    stage: 'refinance',
    requirement: 'bank_requested',
    applicability: 'Refinansowanie kredytu hipotecznego z innego banku.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.refinanceGuide,
    evidence: 'case_specific_bank_request',
    notes: [
      'Publiczna strona nie publikuje zamkniętej listy ani osobnego formularza Pekao.',
      'Nie blokować sprawy sztucznym PDF-em: ekspert ma uzyskać z banku refinansowanego aktualne saldo/kwotę spłaty, rachunek do spłaty oraz dokument zwolnienia/wykreślenia hipoteki zgodnie z indywidualną listą Pekao.',
      'Umowę kredytu i historię spłat dołączać tylko, gdy Bank ich zażąda.',
    ],
  },
  {
    code: 'property_insurance_policy_and_payment',
    title: 'Polisa ubezpieczenia nieruchomości i potwierdzenie opłacenia składki',
    scope: 'case',
    stage: 'insurance',
    requirement: 'conditional',
    applicability: 'Po zawarciu umowy i następnie w każdym wymaganym okresie ochrony.',
    validity: 'Zgodnie z okresem ochrony na polisie; dokument odnawiany na kolejne okresy.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.existingMortgage,
    evidence: 'official_product_page',
    notes: ['Ubezpieczyciela zweryfikować z aktualną listą Banku.'],
  },
  {
    code: 'contract_specific_disbursement_conditions',
    title: 'Dokumenty potwierdzające spełnienie warunków wypłaty',
    scope: 'case',
    stage: 'disbursement',
    requirement: 'bank_requested',
    applicability: 'Przed każdą wypłatą lub transzą zgodnie z umową kredytu.',
    validity: null,
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.existingMortgage,
    evidence: 'case_specific_bank_request',
    notes: ['Lista zależy od umowy; nie zastępuje jej publiczny formularz wniosku o wypłatę.'],
  },
] as const satisfies readonly PekaoClientDocumentRequirement[]

export interface PekaoManualAction {
  code: string
  kind: 'manual_action' | 'web_form' | 'external_check'
  title: string
  applicability: string
  sourceUrl: string
  blocking: boolean
  notes: readonly string[]
}

export const PEKAO_MANUAL_ACTIONS = [
  {
    code: 'rkm_eligibility_verification',
    kind: 'manual_action',
    title: 'Zweryfikuj warunki Rodzinnego Kredytu Mieszkaniowego i gwarancji BGK',
    applicability: 'Gdy wybrano RKM / kredyt bez wkładu własnego.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.familyMortgage,
    blocking: true,
    notes: ['Na publicznej stronie Pekao nie znaleziono osobnego aktualnego PDF-u do wypełnienia; nie tworzyć fikcyjnego formularza.'],
  },
  {
    code: 'big_krd_checks_from_kik',
    kind: 'external_check',
    title: 'Wykonaj kontrole BIG InfoMonitor i KRD na podstawie podpisanej Karty Informacyjnej',
    applicability: 'Każdy wnioskodawca.',
    sourceUrl: PEKAO_COMPLETE_PACKAGE_DOCUMENTS[1].downloadUrl,
    blocking: true,
    notes: ['Upoważnienia formularza obowiązują maksymalnie 60 dni; kontrola jest czynnością Banku, nie załącznikiem PDF.'],
  },
  {
    code: 'limited_online_mortgage_application',
    kind: 'web_form',
    title: 'Wniosek hipoteczny online Pekao',
    applicability: 'Tylko klient z PESEL, rachunkiem Pekao z wpływem wynagrodzenia z umowy o pracę, jednym gospodarstwem lub rozdzielnością, zakupem mieszkania z rynku wtórnego, kwotą do 500 000 zł i LTV do 80%.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.mortgage,
    blocking: false,
    notes: ['Ścieżkę reprezentować jako web_form; nie generować duplikatu papierowego wniosku.'],
  },
  {
    code: 'refinance_document_list_confirmation',
    kind: 'manual_action',
    title: 'Potwierdź indywidualną listę dokumentów refinansowania w Pekao',
    applicability: 'Refinansowanie kredytu z innego banku.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.refinanceGuide,
    blocking: true,
    notes: ['Publiczna strona opisuje proces, ale nie publikuje zamkniętej listy wymaganych zaświadczeń.'],
  },
  {
    code: 'tranche_conditions_confirmation',
    kind: 'manual_action',
    title: 'Zweryfikuj warunki uruchomienia wypłaty/transzy z umowy kredytu',
    applicability: 'Każda wypłata po zawarciu umowy.',
    sourceUrl: PEKAO_OFFICIAL_SOURCE_PAGES.existingMortgage,
    blocking: true,
    notes: ['Sam podpisany wniosek o wypłatę nie potwierdza spełnienia warunków umownych.'],
  },
] as const satisfies readonly PekaoManualAction[]

/** Canonical fields needed to automate the currently manual Pekao forms. */
export const PEKAO_CANONICAL_KEYS_TO_ADD = [
  'applicants.*.motherMaidenName',
  'applicants.*.fatherFirstName',
  'applicants.*.motherFirstName',
  'applicants.*.identityDocumentExpiryDate',
  'applicants.*.identityDocumentIndefinite',
  'applicants.*.euResidenceRegistrationNumber',
  'applicants.*.euResidenceRegistrationExpiryDate',
  'applicants.*.gender',
  'applicants.*.dependentChildrenCount',
  'applicants.*.otherCitizenship',
  'applicants.*.yearsInPoland',
  'applicants.*.monthsInPoland',
  'applicants.*.yearsAtResidentialAddress',
  'applicants.*.totalEmploymentYears',
  'applicants.*.totalEmploymentMonths',
  'applicants.*.employerPhone',
  'applicants.*.employerEntityType',
  'applicants.*.employerLegalForm',
  'applicants.*.fixedNetIncome',
  'applicants.*.variableNetIncomeLast12Months',
  'applicants.*.employmentNoticePeriodActive',
  'applicants.*.salaryGarnishmentReason',
  'pekao.consents.iadElectronicDelivery',
  'pekao.consents.bigInfoMonitor',
  'pekao.consents.krd',
  'pekao.declarations.bankruptcy',
  'pekao.declarations.creditHoliday',
  'pekao.declarations.pep',
  'pekao.business.*',
  'pekao.business.taxationChange.*',
  'pekao.relatedCompany.*',
  'pekao.agriculturalBusiness.*',
  'property.classification',
  'property.agriculturalUse',
  'property.agriculturalHoldingArea',
  'loan.contractNumber',
  'pekao.disbursement.*',
  'pekao.costEstimate.*',
] as const

export const PEKAO_CURRENT_TEMPLATE_DRIFT = {
  existingTemplateId: 'pekao-mortgage-2025',
  existingSourceFileName: 'pekao-wniosek-o-kredyt-mieszkaniowy.pdf',
  existingSourceSha256: 'f9d16ec8fc7810c9b8e6301eeb8e0b9c190d9ebc3f29acb356648bf1f06f79bc',
  currentSourceFileName: 'pekao-wniosek-o-kredyt-mieszkaniowy-2026-06-02.pdf',
  currentSourceSha256: '735c8457af4dec79c31ccb702fd3c2b77a5fdb57939781f5476a04fdd667374a',
  existingAcroFormFieldCount: 287,
  currentAcroFormFieldCount: 279,
  removedFieldNames: ['C42', 'C43', 'C44', 'C85', 'C86', 'C103', 'C104', 'C105'],
  geometryChangedFieldNames: [
    'Text Field 55',
    'Text Field 57',
    'Text Field 59',
    'Text Field 60',
    'Text Field 61',
    'Text Field 62',
    'Text Field 63',
    'Text Field 64',
    'Text Field 65',
    'Text Field 66',
    'Text Field 67',
    'Text Field 68',
    'Text Field 141',
    'Text Field 142',
    'Text Field 143',
    'C45',
    'C46',
    'C47',
    'C48',
    'C49',
    'C50',
    'C51',
    'C52',
    'C83',
    'C84',
    'C87',
    'C88',
    'C89',
    'C90',
  ],
  requiredRemediation: [
    'Przepiąć aktywny template na bieżący, datowany plik i hash.',
    'Usunąć osiem nieistniejących bindingów oraz zaktualizować liczniki pokrycia z 278 do 270 pól klienta.',
    'Ponownie wygenerować i wizualnie zatwierdzić snapshoty 29 pól o zmienionej geometrii.',
    'Zaktualizować testy renderowania, które nadal oczekują pól C42/C43/C103/C104.',
  ],
} as const
