/**
 * PKO BP / PKO Bank Hipoteczny mortgage-package audit.
 *
 * Checked against public, bank-owned sources on 2026-08-09. This catalogue is
 * deliberately bank-specific and is not wired into the shared registry here.
 * It distinguishes downloadable official PDFs from customer evidence,
 * bank-generated documents, the digital web flow and post-contract actions.
 */

export const PKO_COMPLETE_PACKAGE_CHECKED_AT = '2026-08-09' as const

export const PKO_OFFICIAL_SOURCE_PAGES = {
  mortgage: 'https://www.pkobp.pl/klient-indywidualny/kredyty-pozyczki/kredyt-hipoteczny',
  familyMortgage: 'https://www.pkobp.pl/klient-indywidualny/kredyty-pozyczki/kredyt-mieszkaniowy-splata-rodzinna',
  pkoBhMortgage: 'https://www.pkobh.pl/kredyt-hipoteczny-pko-banku-hipotecznego',
  onlineDispositions: 'https://www.pkobp.pl/klient-indywidualny/aplikacja-iko-ipko/dyspozycje',
} as const

export type PkoPackageMethod =
  | 'pdf_acroform'
  | 'pdf_manual'
  | 'pdf_readonly'
  | 'web_form'
  | 'bank_generated'
  | 'manual_action'
  | 'customer_upload'

export type PkoPackageScope =
  | 'case'
  | 'each_applicant'
  | 'each_relevant_applicant'
  | 'each_income_source'
  | 'each_property'
  | 'each_liability'
  | 'reference'

export type PkoPackageStage =
  | 'application'
  | 'income'
  | 'property'
  | 'information_delivery'
  | 'decision'
  | 'pre_disbursement'
  | 'post_contract'

export interface PkoOfficialPdfAsset {
  readonly fileName: string
  readonly sha256: string
  readonly pageCount: number
  readonly acroFormFieldCount: number
  readonly customerControlCount: number
  readonly technicalButtonCount: number
  readonly publishedOrModifiedDate: string | null
  readonly observedCurrentAt: '2026-08-09'
  readonly downloadUrl: `https://${string}`
}

export interface PkoOfficialPackageDocument {
  readonly id: string
  readonly title: string
  readonly method: Extract<PkoPackageMethod, 'pdf_acroform' | 'pdf_manual' | 'pdf_readonly' | 'web_form'>
  readonly scope: PkoPackageScope
  readonly stage: PkoPackageStage
  readonly requiredWhen: readonly string[]
  readonly sourcePageUrl: `https://${string}`
  readonly asset?: PkoOfficialPdfAsset
  readonly validity: string
  readonly signatures: readonly string[]
  readonly canonicalKeys: readonly string[]
  readonly notes: readonly string[]
}

const standardPage = PKO_OFFICIAL_SOURCE_PAGES.mortgage
const rkmPage = PKO_OFFICIAL_SOURCE_PAGES.familyMortgage
const pkoBhPage = PKO_OFFICIAL_SOURCE_PAGES.pkoBhMortgage

export const PKO_OFFICIAL_PACKAGE_DOCUMENTS = [
  {
    id: 'pko-standard-mortgage-application-2025-09-30',
    title: 'Wniosek o udzielenie kredytu lub pożyczki',
    method: 'pdf_acroform',
    scope: 'case',
    stage: 'application',
    requiredWhen: ['papierowy/ekspercki wniosek Własny Kąt, MIX albo pożyczka hipoteczna'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-wniosek-o-kredyt-hipoteczny-2025-09-30.pdf',
      sha256: 'c6ee2244dee8959613b4fc1ae07e1a49878b47a0ba28f1a97aee7e164de6af3c',
      pageCount: 4,
      acroFormFieldCount: 182,
      customerControlCount: 144,
      technicalButtonCount: 38,
      publishedOrModifiedDate: '2025-09-30',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/0846452c-90a7-47e1-8e07-aec958a5c63f.pdf',
    },
    validity: 'Używać bieżącej rewizji banku; ten plik obowiązuje od 30.09.2025 r.',
    signatures: [
      'Każdy aktywny wnioskodawca podpisuje wniosek.',
      'Data wpływu, numer kontraktu i dane osoby przyjmującej są polami banku/pośrednika.',
    ],
    canonicalKeys: ['applicants.*', 'loan.*', 'investment.*', 'property.*', 'collateralProperties.*', 'additionalProducts.*'],
    notes: [
      'Ten sam wniosek Własny Kąt jest składany do PKO BP i PKO BH; najpierw rozpatruje go PKO BH.',
      'MIX i pożyczka hipoteczna pozostają ścieżkami PKO BP.',
      'Istniejący PKO_TEMPLATE mapuje wszystkie 144 kontrolki klienta; cztery podpisy pozostają ręczne.',
      'PKO BH publikuje ten sam formularz pod własnym adresem (12dc1b7c-3406-4ee3-a128-e3be28931660): 182 nazwy pól są identyczne, ale bajty i geometria 22 adnotacji różnią się, dlatego paczka używa jednej zweryfikowanej dystrybucji PKO BP zamiast dublować wniosek.',
    ],
  },
  {
    id: 'pko-digital-mortgage-application-2026',
    title: 'Cyfrowy Kredyt Hipoteczny — wniosek bankowy online',
    method: 'web_form',
    scope: 'case',
    stage: 'application',
    requiredWhen: ['klient wybrał proces Cyfrowego Kredytu Hipotecznego w iPKO'],
    sourcePageUrl: standardPage,
    validity: 'Bank utrzymuje wersję i sesję formularza w swoim kanale; nie ma publicznego pustego PDF-u do zastąpienia.',
    signatures: ['Wniosek i umowa są zatwierdzane w bankowym procesie online; podpis umowy może prowadzić przez mSzafir.'],
    canonicalKeys: ['application.submissionChannel', 'applicants.*', 'loan.*', 'investment.*', 'property.*'],
    notes: [
      'Nie generować syntetycznego PDF-u. System powinien otworzyć/śledzić bankowy web_form i przyjąć wygenerowane potwierdzenie.',
      'Ścieżka publicznie obejmuje jednego lub dwóch wnioskodawców i tylko cele/dochody dopuszczone przez bankowy kwalifikator.',
    ],
  },
  {
    id: 'pko-applicant-data-2026-05-21',
    title: 'Załącznik do wniosku — dane wnioskodawcy',
    method: 'pdf_manual',
    scope: 'each_applicant',
    stage: 'application',
    requiredWhen: ['każdy papierowy/ekspercki wniosek, osobny egzemplarz dla każdego wnioskodawcy'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-dane-wnioskodawcy-2026-05-21.pdf',
      sha256: 'b5daf158bdedb93e3e21be1a77e513dd753ef45b9d9f7ce5d07d6fe98bfa6ac9',
      pageCount: 2,
      acroFormFieldCount: 107,
      customerControlCount: 89,
      technicalButtonCount: 18,
      publishedOrModifiedDate: '2026-05-21',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/7d974db7-b6fc-48e6-91fc-5e66f8962fcc.pdf',
    },
    validity: 'Upoważnienie BIG/BIK w formularzu jest ważne 60 dni; pozostałe dane muszą być aktualne przy złożeniu.',
    signatures: ['Wnioskodawca wybiera zgody i podpisuje formularz.', 'Pracownik potwierdza tożsamość i uzupełnia pola bankowe.'],
    canonicalKeys: ['applicants.*', 'households.*', 'liabilities.*', 'consents.*'],
    notes: [
      'Pełny snapshot 107 kontrolek znajduje się w pko-package-field-audit.json; do czasu semantycznego mapowania formularz jest pdf_manual.',
      'PKO BH publikuje równoważny plik pod adresem de41d296-b1e0-4cb7-bba5-f55c07281fb3: nazwy wszystkich 107 pól są identyczne; nie dołączamy drugiej kopii do tej samej sprawy.',
    ],
  },
  {
    id: 'pko-liabilities-to-repay-2025-09-30',
    title: 'Informacje o zobowiązaniach przewidzianych do spłaty',
    method: 'pdf_manual',
    scope: 'each_relevant_applicant',
    stage: 'application',
    requiredWhen: ['wnioskodawca spłaca lub zamyka zobowiązania ze środków kredytu albo na warunek decyzji PKO BP'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-zobowiazania-do-splaty-2025-09-30.pdf',
      sha256: 'f7404610c44ad0cafcf4a69977d957c11bdc30f25adc093f7703d3918bb8ed8a',
      pageCount: 1,
      acroFormFieldCount: 68,
      customerControlCount: 59,
      technicalButtonCount: 9,
      publishedOrModifiedDate: '2025-09-30',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/a4270477-2235-463b-bdb1-80d96fdb966c.pdf',
    },
    validity: 'Dane i salda muszą odpowiadać stanowi na dzień składania; bank może wymagać aktualnego zaświadczenia wierzyciela.',
    signatures: ['Podpisuje każdy wnioskodawca, którego zobowiązania są wykazane.', 'Pola wpływu i przyjęcia uzupełnia bank/pośrednik.'],
    canonicalKeys: ['applicants.*.liabilities.*', 'application.hasLiabilitiesToRepay'],
    notes: ['Formularz wskazuje, że nie dotyczy PKO BH; zachować go dla rozpatrzenia przez PKO BP.'],
  },
  {
    id: 'pko-mortgage-place-2025-05-13',
    title: 'Opróżnione miejsce hipoteczne / zabezpieczenie wielu wierzytelności',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['opróżnione miejsce hipoteczne, zastąpienie wierzytelności albo jeden wpis dla wielu wierzytelności w PKO BP'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-oproznione-miejsce-hipoteczne-2025-05-13.pdf',
      sha256: 'a5e58f1d3469661391da9d01d7d3eb8cd0f465efdbf45b899ccc51f673fecbd1',
      pageCount: 1,
      acroFormFieldCount: 42,
      customerControlCount: 31,
      technicalButtonCount: 11,
      publishedOrModifiedDate: '2025-05-13',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/ee66ca85-2c99-455d-aeac-0ad0fa374a09.pdf',
    },
    validity: 'Per aktualny stan księgi wieczystej i wierzytelności.',
    signatures: ['Wnioskodawcy podpisują część kliencką; pola przyjęcia są bankowe.'],
    canonicalKeys: ['property.landRegisterNumber', 'property.mortgages.*', 'property.requiresMortgageDischargeAnnex'],
    notes: ['Formularz nie dotyczy PKO BH.'],
  },
  {
    id: 'pko-owned-properties-2025-05-13',
    title: 'Informacja o posiadanych nieruchomościach',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'application',
    requiredWhen: ['co najmniej jeden wnioskodawca posiada inną nieruchomość mieszkalną'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-posiadane-nieruchomosci-2025-05-13.pdf',
      sha256: '4bc0ea6843b97e313fc3777b2ead7d52a6ce0f25d55192b1002e19bf23ee25c3',
      pageCount: 1,
      acroFormFieldCount: 45,
      customerControlCount: 37,
      technicalButtonCount: 8,
      publishedOrModifiedDate: '2025-05-13',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/aafbd526-244c-4ba1-bede-aba4115ec7fb.pdf',
    },
    validity: 'Aktualny stan własności i kosztów utrzymania.',
    signatures: ['Podpisują wnioskodawcy, których informacja dotyczy.'],
    canonicalKeys: ['application.hasOtherResidentialProperties', 'ownedResidentialProperties.*'],
    notes: ['Obsługuje pięć nieruchomości i czterech wnioskodawców.'],
  },
  {
    id: 'pko-employment-certificate-current-2026-08-09',
    title: 'Zaświadczenie o zatrudnieniu',
    method: 'pdf_manual',
    scope: 'each_income_source',
    stage: 'income',
    requiredWhen: ['bank lub klient wybiera potwierdzenie dochodu przez pracodawcę'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-zaswiadczenie-o-zatrudnieniu-current-2026-08-09.pdf',
      sha256: '3966fb8c94d17fe84eda7447046704b89494360bda3930ae691c19ae336e6674',
      pageCount: 1,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/764674ac-22d8-4f28-8628-86424b679b7a.pdf',
    },
    validity: '30 dni od wystawienia.',
    signatures: ['Pracodawca/osoba upoważniona podpisuje z funkcją; dopuszczony jest kwalifikowany podpis elektroniczny.'],
    canonicalKeys: ['applicants.*.employment.*', 'applicants.*.income.*'],
    notes: ['PKO publicznie wskazuje, że obecnie może wystarczyć oświadczenie klienta; zaświadczenie pozostaje alternatywą lub żądaniem banku.'],
  },
  {
    id: 'pko-employment-declaration-current-2026-08-09',
    title: 'Oświadczenie o zatrudnieniu',
    method: 'pdf_manual',
    scope: 'each_income_source',
    stage: 'income',
    requiredWhen: ['wnioskodawca korzysta z uproszczonego potwierdzenia zatrudnienia zamiast zaświadczenia pracodawcy'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-oswiadczenie-o-zatrudnieniu-current-2026-08-09.pdf',
      sha256: '2a3cb8cdbdaf648c45df1cc53ea66d0d46ecb144946776ab165d80154f42e0f0',
      pageCount: 1,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/583fa40d-7269-4615-920c-bba41eb232e1.pdf',
    },
    validity: '30 dni od wypełnienia.',
    signatures: ['Wnioskodawca podpisuje oświadczenie i upoważnienie obu banków do weryfikacji danych u pracodawcy.'],
    canonicalKeys: ['applicants.*.employment.*', 'applicants.*.income.*'],
    notes: ['Formularz jest płaskim PDF-em i musi pozostać ręcznie uzupełniany/podpisywany.'],
  },
  {
    id: 'pko-house-cost-estimate-2025-07-31',
    title: 'Kosztorys budowlany — dom jednorodzinny',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['budowa, dokończenie, rozbudowa albo remont domu wymagający kosztorysu'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-kosztorys-dom-2025-07-31.pdf',
      sha256: '4a33f74684a4c6ff43337d9718e3db8955bc853af97241658565ecfae6e34b3c',
      pageCount: 2,
      acroFormFieldCount: 141,
      customerControlCount: 127,
      technicalButtonCount: 14,
      publishedOrModifiedDate: '2025-07-31',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/fbf9cb30-e470-4990-ab1b-e063803a8fbb.pdf',
    },
    validity: 'Per bieżący zakres, ceny, stan zaawansowania i harmonogram inwestycji.',
    signatures: ['Wersję papierową podpisują wnioskodawcy; bank wskazuje, że kosztorys dodany w iPKO nie wymaga podpisu.'],
    canonicalKeys: ['property.construction.*', 'investment.costEstimate.*'],
    notes: ['Do czasu audytu 127 kontrolek klienta pozostaje pdf_manual.'],
  },
  {
    id: 'pko-apartment-cost-estimate-2024-04-15',
    title: 'Kosztorys budowlany — lokal mieszkalny',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['wykończenie albo remont lokalu mieszkalnego wymagający kosztorysu'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-kosztorys-lokal-2024-04-15.pdf',
      sha256: '35ca51628d55bb1b385e1e210e3150aca6683863c568fe0bc294349d80678a7e',
      pageCount: 1,
      acroFormFieldCount: 63,
      customerControlCount: 51,
      technicalButtonCount: 12,
      publishedOrModifiedDate: '2024-04-15',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/9ebdf9f4-23cf-4c5f-bff5-46bfc5aa4f74.pdf',
    },
    validity: 'Per bieżący zakres i ceny prac.',
    signatures: ['Wersję papierową podpisują wnioskodawcy; kosztorys dodany w iPKO nie wymaga podpisu.'],
    canonicalKeys: ['property.renovation.*', 'investment.costEstimate.*'],
    notes: ['Do czasu audytu 51 kontrolek klienta pozostaje pdf_manual.'],
  },
  {
    id: 'pko-risk-information-current-2026-08-09',
    title: 'Informacja o ryzyku stopy procentowej i zmiany cen nieruchomości',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['każdy standardowy wniosek hipoteczny'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-informacja-o-ryzyku-current-2026-08-09.pdf',
      sha256: '27ad72da6380e7c1177c0696c1a415ab55a1f0e7c48699ddf7dadc672000b3a5',
      pageCount: 6,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/57dac63c-fc98-4eba-a635-83092ef14b79.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję przed złożeniem/podpisaniem oświadczeń z wniosku.',
    signatures: [],
    canonicalKeys: [],
    notes: ['Read-only; nie liczyć jako automatycznie uzupełnionego formularza.'],
  },
  {
    id: 'pko-bp-general-information-current-2026-08-09',
    title: 'Informacje ogólne — PKO Bank Polski',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['standardowa ścieżka PKO BP lub zapasowe rozpatrzenie Własnego Kąta przez PKO BP'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-informacje-ogolne-current-2026-08-09.pdf',
      sha256: '82654df4021c207f5179ec5c01c5721fb0671a348c406ba09c1be2d31dce1383',
      pageCount: 7,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/68ba37cb-8d4a-44a6-a69c-1ab423a33156.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję.',
    signatures: [],
    canonicalKeys: [],
    notes: ['Read-only; opisuje m.in. bankową ocenę wartości nieruchomości i warunki przyjęcia operatu klienta.'],
  },
  {
    id: 'pko-bh-general-information-current-2026-08-09',
    title: 'Informacje ogólne — PKO Bank Hipoteczny',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['Własny Kąt rozpatrywany najpierw przez PKO BH'],
    sourcePageUrl: pkoBhPage,
    asset: {
      fileName: 'pko-bh-informacje-ogolne-current-2026-08-09.pdf',
      sha256: '26e0da5b05a378e11d7c78265334e8ad1616cf3ddea6a0706b32f35f5f4b1a86',
      pageCount: 6,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobh.pl/api/public/24cd4a91-2821-4fb5-8b8c-66dec6af37ef.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję.',
    signatures: [],
    canonicalKeys: [],
    notes: ['PKO BH wykonuje bankowo-hipoteczną ekspertyzę wartości na własny koszt i nie wymaga operatu klienta.'],
  },
  {
    id: 'pko-benchmark-fallback-current-2026-08-09',
    title: 'Plan awaryjny wskaźnika referencyjnego — PKO Bank Polski',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['każdy standardowy wniosek rozpatrywany przez PKO BP'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-plan-awaryjny-wskaznika-current-2026-08-09.pdf',
      sha256: '5a611397f635503511129610ed42fda2df363ac6d83ed521e4b12d5fc420bc36',
      pageCount: 2,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/efaabf29-84a6-489d-bcbf-18d36f3ad277.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję.',
    signatures: [],
    canonicalKeys: [],
    notes: ['Treść wskazuje działania PKO BP; nie zastępuje odrębnego planu PKO Banku Hipotecznego.'],
  },
  {
    id: 'pko-bh-benchmark-fallback-current-2026-08-09',
    title: 'Plan awaryjny wskaźnika referencyjnego — PKO Bank Hipoteczny',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['Własny Kąt składany do obu banków i rozpatrywany najpierw przez PKO BH'],
    sourcePageUrl: pkoBhPage,
    asset: {
      fileName: 'pko-bh-plan-awaryjny-wskaznika-current-2026-08-09.pdf',
      sha256: '458493c0d23732f9a4ca241f614e44e809cfd438309c981ee8518345cab4066f',
      pageCount: 2,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2025-04-07',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobh.pl/api/public/e1c37829-cb57-438f-9db7-db4cfe3bd2c8.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla PKO Banku Hipotecznego.',
    signatures: [],
    canonicalKeys: [],
    notes: ['Odrębna treść od planu PKO BP; wskazuje PKO BH jako podmiot dokonujący zamiany wskaźnika i przekazujący informacje klientowi.'],
  },
  {
    id: 'pko-interest-types-current-2026-08-09',
    title: 'Uproszczona informacja o rodzajach oprocentowania',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['każdy standardowy wniosek hipoteczny'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-uproszczona-informacja-oprocentowanie-current-2026-08-09.pdf',
      sha256: '81b46852ed838bf51e5c20cf73be0a590943e39aeaa395e5827f863038109f2f',
      pageCount: 1,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/5e1afd54-6cd6-412d-9997-5c1a4871cc58.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję.',
    signatures: [],
    canonicalKeys: [],
    notes: ['Wniosek zawiera potwierdzenie otrzymania tego dokumentu.'],
  },
  {
    id: 'pko-fixed-rate-information-current-2026-08-09',
    title: 'Informacja o stałej stopie procentowej',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['oprocentowanie okresowo stałe w pierwszym okresie pięcioletnim'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-informacja-stala-stopa-current-2026-08-09.pdf',
      sha256: '183a737b24cbd2b7ef233225bdf29811fb6e767311e895dce8303e1bd543731e',
      pageCount: 2,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/ebf204ce-f7a2-4ff0-95d3-bbf26bfe8102.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla wybranej stopy.',
    signatures: [],
    canonicalKeys: ['loan.interestType'],
    notes: ['Wniosek zawiera potwierdzenie otrzymania tego dokumentu.'],
  },
  {
    id: 'pko-rkm-eligibility-declaration-2026-07-10',
    title: 'RKM — oświadczenie o spełnieniu warunków ustawy',
    method: 'pdf_manual',
    scope: 'each_applicant',
    stage: 'application',
    requiredWhen: ['Rodzinny Kredyt Mieszkaniowy'],
    sourcePageUrl: rkmPage,
    asset: {
      fileName: 'pko-bp-rkm-oswiadczenie-warunki-2026-07-10.pdf',
      sha256: 'de170d199f629085251c32af1ee5740fffc45cf278c8c088b5c8a843265d763e',
      pageCount: 7,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2026-07-10',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/9674e7d5-3cfd-4eb1-83b3-c8f0d08cb2d5.pdf',
    },
    validity: 'Dane i warunki ustawowe na dzień złożenia wniosku.',
    signatures: ['Każda osoba ubiegająca się o RKM składa własne oświadczenie i podpisuje je.'],
    canonicalKeys: ['loan.program', 'applicants.*.rkmEligibility.*', 'households.*'],
    notes: ['Płaski PDF — pdf_manual; obejmuje oświadczenia, zgody BGK i informacje o odpowiedzialności za dane.'],
  },
  {
    id: 'pko-rkm-family-repayment-conditions-2026-07-10',
    title: 'RKM — warunki uzyskania kredytu i spłaty rodzinnej',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['Rodzinny Kredyt Mieszkaniowy'],
    sourcePageUrl: rkmPage,
    asset: {
      fileName: 'pko-bp-rkm-warunki-splaty-rodzinnej-2026-07-10.pdf',
      sha256: 'e949d89c84f4741f12447c4c2641a2b736b4466459a60eb7e5d9ded1f78bcccc',
      pageCount: 13,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2026-07-10',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/c48e52f7-b637-4bd5-9267-d1a90be575dd.pdf',
    },
    validity: 'Doręczyć rewizję właściwą dla dnia składania.',
    signatures: [],
    canonicalKeys: ['loan.program'],
    notes: ['Read-only załącznik do oświadczenia ustawowego.'],
  },
  {
    id: 'pko-rkm-guarantee-conditions-2026-07-10',
    title: 'RKM — warunki gwarancji spłaty BGK',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['Rodzinny Kredyt Mieszkaniowy z gwarancją BGK'],
    sourcePageUrl: rkmPage,
    asset: {
      fileName: 'pko-bp-rkm-warunki-gwarancji-bgk-2026-07-10.pdf',
      sha256: 'f3d19b0ec95e7dc5825c01f1ce440beae96da7352704005bac03a2b92c5ed4a3',
      pageCount: 8,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2026-07-10',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/878f6a2f-4347-4a3a-b1b8-2f51fcf8708e.pdf',
    },
    validity: 'Doręczyć rewizję właściwą dla dnia składania.',
    signatures: [],
    canonicalKeys: ['loan.rkmGuarantee'],
    notes: [],
  },
  {
    id: 'pko-rkm-guarantee-application-current-2026-08-09',
    title: 'RKM — wniosek o udzielenie przez BGK gwarancji',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'application',
    requiredWhen: ['Rodzinny Kredyt Mieszkaniowy z gwarancją BGK'],
    sourcePageUrl: rkmPage,
    asset: {
      fileName: 'pko-bp-rkm-wniosek-gwarancja-bgk-current-2026-08-09.pdf',
      sha256: 'df0b01606b5c5badf387610acd31e40e071fd2d43239076c761e42f0d1adad6a',
      pageCount: 3,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: null,
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/93e1145d-edea-4e9c-8c71-2809cfda6f0f.pdf',
    },
    validity: 'Dane i parametry gwarancji aktualne na dzień wniosku; wartości końcowe zależą od decyzji banku.',
    signatures: ['Podpisują wszyscy kredytobiorcy objęci wnioskiem o gwarancję.'],
    canonicalKeys: ['loan.rkmGuarantee', 'loan.amount', 'investment.ownFunds', 'rkm.guarantee.*'],
    notes: ['Płaski PDF — pdf_manual.'],
  },
  {
    id: 'pko-rkm-post-contract-family-repayment-2026-07-10',
    title: 'RKM — zlecenie spłaty rodzinnej',
    method: 'pdf_manual',
    scope: 'case',
    stage: 'post_contract',
    requiredWhen: ['wyłącznie po uruchomieniu RKM i wystąpieniu zdarzenia uprawniającego do spłaty rodzinnej'],
    sourcePageUrl: rkmPage,
    asset: {
      fileName: 'pko-bp-rkm-zlecenie-splaty-rodzinnej-2026-07-10.pdf',
      sha256: 'b85deb6fd61d69def2f0919c991bfea9e40b72aa29656d361607b56a666d47c9',
      pageCount: 2,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2026-07-10',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/dbb8a136-2568-4490-99ab-4f176bedec13.pdf',
    },
    validity: 'Per aktualne zdarzenie rodzinne i aktywny kredyt.',
    signatures: ['Podpisują kredytobiorcy zgodnie z instrukcją formularza.'],
    canonicalKeys: ['postContract.familyRepaymentRequested', 'postContract.familyEvent.*'],
    notes: ['Nigdy nie blokuje gotowości pierwotnego wniosku; to osobny etap po umowie.'],
  },
  {
    id: 'pko-digital-risk-information-current-2026-08-09',
    title: 'Cyfrowy Kredyt Hipoteczny — informacja o ryzyku',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['bankowy proces Cyfrowego Kredytu Hipotecznego'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-cyfrowy-informacja-o-ryzyku-current-2026-08-09.pdf',
      sha256: 'f592fb6113ea435bfc7e0928df70ebc27607ea517095f8bf0b727fdd3e8297b5',
      pageCount: 6,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2025-12-17',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/233909a0-298d-4ce5-9562-25c72e6f8fc4.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla procesu cyfrowego.',
    signatures: [],
    canonicalKeys: ['application.submissionChannel'],
    notes: ['Nie mieszać ze standardowym dokumentem ryzyka.'],
  },
  {
    id: 'pko-digital-fixed-rate-information-current-2026-08-09',
    title: 'Cyfrowy Kredyt Hipoteczny — informacja o stałej stopie',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['proces cyfrowy i oprocentowanie okresowo stałe'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-cyfrowy-informacja-stala-stopa-current-2026-08-09.pdf',
      sha256: 'e57a87263a47dabfd2c145c8c0a82b5e0b8ad78df1ce59e5f3b7156417d3421d',
      pageCount: 1,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2025-02-06',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/091724fe-f74e-4dcf-82a9-45cc124885c9.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla procesu cyfrowego.',
    signatures: [],
    canonicalKeys: ['application.submissionChannel', 'loan.interestType'],
    notes: [],
  },
  {
    id: 'pko-digital-interest-types-current-2026-08-09',
    title: 'Cyfrowy Kredyt Hipoteczny — uproszczona informacja o oprocentowaniu',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['bankowy proces Cyfrowego Kredytu Hipotecznego'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-cyfrowy-uproszczona-informacja-oprocentowanie-current-2026-08-09.pdf',
      sha256: '685a7498c5be908dbf81e6be03640d765e9c22acc8edd3869621eb945f76e614',
      pageCount: 1,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2024-09-20',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/14976336-77b9-4b72-b398-0c8d5ec83e9c.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla procesu cyfrowego.',
    signatures: [],
    canonicalKeys: ['application.submissionChannel'],
    notes: [],
  },
  {
    id: 'pko-digital-general-information-2026-07-23',
    title: 'Informacje ogólne o Cyfrowym Kredycie Hipotecznym',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['bankowy proces Cyfrowego Kredytu Hipotecznego'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-cyfrowy-informacje-ogolne-current-2026-08-09.pdf',
      sha256: 'dbc22871141de92b32eca8ad3767d88e85848f92452cd743be15b16773429b55',
      pageCount: 5,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2026-07-23',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/7af546c2-00d2-4687-a047-a51ea916ec66.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla procesu cyfrowego.',
    signatures: [],
    canonicalKeys: ['application.submissionChannel'],
    notes: ['Nie zastępuje informacji ogólnych dla papierowego Własnego Kąta.'],
  },
  {
    id: 'pko-digital-benchmark-fallback-current-2026-08-09',
    title: 'Cyfrowy Kredyt Hipoteczny — plan awaryjny wskaźnika',
    method: 'pdf_readonly',
    scope: 'case',
    stage: 'information_delivery',
    requiredWhen: ['bankowy proces Cyfrowego Kredytu Hipotecznego'],
    sourcePageUrl: standardPage,
    asset: {
      fileName: 'pko-bp-cyfrowy-plan-awaryjny-wskaznika-current-2026-08-09.pdf',
      sha256: '64bb31541ced22f6c0cf136e926ce492ddb8f421d8ad9ae353ec109c934fe23e',
      pageCount: 2,
      acroFormFieldCount: 0,
      customerControlCount: 0,
      technicalButtonCount: 0,
      publishedOrModifiedDate: '2025-04-08',
      observedCurrentAt: '2026-08-09',
      downloadUrl: 'https://www.pkobp.pl/api/public/5e4a3da2-72fe-4afc-b92c-30c14c51fcab.pdf',
    },
    validity: 'Doręczyć bieżącą rewizję właściwą dla procesu cyfrowego.',
    signatures: [],
    canonicalKeys: ['application.submissionChannel'],
    notes: [],
  },
] as const satisfies readonly PkoOfficialPackageDocument[]

export interface PkoCaseRequirement {
  readonly id: string
  readonly title: string
  readonly method: Extract<PkoPackageMethod, 'bank_generated' | 'manual_action' | 'customer_upload'>
  readonly scope: PkoPackageScope
  readonly stage: PkoPackageStage
  readonly requiredWhen: readonly string[]
  readonly blocksApplication: boolean
  readonly evidence: readonly string[]
  readonly canonicalKeys: readonly string[]
  readonly notes: readonly string[]
}

/**
 * Evidence and bank steps that have no stable public PKO PDF. The system must
 * create checklist actions/uploads, not invent bank forms.
 */
export const PKO_CASE_REQUIREMENTS = [
  {
    id: 'pko-identity-verification',
    title: 'Weryfikacja tożsamości wnioskodawcy',
    method: 'manual_action',
    scope: 'each_applicant',
    stage: 'application',
    requiredWhen: ['każdy wnioskodawca'],
    blocksApplication: true,
    evidence: ['ważny dokument tożsamości okazany w kanale wymaganym przez bank', 'potwierdzenie tożsamości przez pracownika/proces cyfrowy'],
    canonicalKeys: ['applicants.*.identityDocumentType', 'applicants.*.identityDocumentNumber', 'applicants.*.identityDocumentExpiryDate'],
    notes: ['Nie zakładać, że skan dokumentu jest zawsze wymagany; formularz przewiduje potwierdzenie przez pracownika.'],
  },
  {
    id: 'pko-income-evidence',
    title: 'Dowody dochodu właściwe dla każdego źródła',
    method: 'customer_upload',
    scope: 'each_income_source',
    stage: 'income',
    requiredWhen: ['bank nie może potwierdzić dochodu w swoich danych lub żąda dokumentów dla danego źródła'],
    blocksApplication: true,
    evidence: ['wyciągi/zaświadczenia/decyzje/zeznania podatkowe wskazane przez bank dla konkretnego źródła', 'dokumenty aktualne na dzień analizy'],
    canonicalKeys: ['applicants.*.incomeSources.*'],
    notes: ['Poza zatrudnieniem PKO nie publikuje na stronie produktu jednego stałego formularza dla wszystkich źródeł; wymaganie musi pozostać bank_requested.'],
  },
  {
    id: 'pko-income-public-arrears-evidence',
    title: 'Brak zaległości publicznoprawnych / dokumenty działalności',
    method: 'customer_upload',
    scope: 'each_relevant_applicant',
    stage: 'income',
    requiredWhen: ['dochód z działalności gospodarczej, spółki lub gospodarstwa i żądanie banku'],
    blocksApplication: true,
    evidence: ['dokumenty podatkowe i finansowe', 'zaświadczenia ZUS/KRUS/US lub inne dowody braku zaległości wskazane przez bank'],
    canonicalKeys: ['applicants.*.businessIncome.*'],
    notes: ['Nie tworzyć syntetycznego formularza PKO; lista jest dobierana do formy prawnej i opodatkowania.'],
  },
  {
    id: 'pko-secondary-market-transaction-documents',
    title: 'Dokumenty transakcji — rynek wtórny',
    method: 'customer_upload',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['zakup nieruchomości na rynku wtórnym'],
    blocksApplication: true,
    evidence: ['umowa przedwstępna/rezerwacyjna albo inny dokument uzgodniony z bankiem', 'dane tytułu prawnego i księgi wieczystej', 'dokumenty wierzyciela hipotecznego, jeżeli nieruchomość jest obciążona'],
    canonicalKeys: ['loan.purpose', 'property.market', 'property.landRegisterNumber', 'transaction.*'],
    notes: ['PKO weryfikuje księgę wieczystą online; nie wymagać automatycznie papierowego odpisu, jeżeli bank może go pobrać.'],
  },
  {
    id: 'pko-primary-market-transaction-documents',
    title: 'Dokumenty transakcji — rynek pierwotny',
    method: 'customer_upload',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['zakup od dewelopera lub spółdzielni'],
    blocksApplication: true,
    evidence: ['umowa rezerwacyjna/deweloperska lub umowa ze spółdzielnią', 'harmonogram i cena płatności', 'dokumenty inwestycji wskazane przez bank'],
    canonicalKeys: ['loan.purpose', 'property.market', 'transaction.developer.*'],
    notes: ['Dla lokalu w budowie w ścieżce PKO BH wniosek opisuje wpis roszczenia banku do księgi nieruchomości inwestycji.'],
  },
  {
    id: 'pko-construction-legal-documents',
    title: 'Dokumenty prawne i techniczne budowy',
    method: 'customer_upload',
    scope: 'case',
    stage: 'property',
    requiredWhen: ['budowa, rozbudowa, przebudowa lub dokończenie budowy'],
    blocksApplication: true,
    evidence: ['tytuł prawny i księga wieczysta gruntu', 'pozwolenie na budowę albo skuteczne zgłoszenie', 'projekt/dokumentacja budowy wskazana przez bank', 'harmonogram i właściwy kosztorys PKO'],
    canonicalKeys: ['loan.purpose', 'property.construction.*', 'investment.costEstimate.*'],
    notes: ['Bank może kontrolować inwestycję i dokumentację budowy; późniejsze dokumenty zakończenia są osobnym etapem.'],
  },
  {
    id: 'pko-refinance-creditor-documents',
    title: 'Dokumenty wierzyciela dla refinansowania lub spłaty zobowiązań',
    method: 'customer_upload',
    scope: 'each_liability',
    stage: 'application',
    requiredWhen: ['refinansowanie kredytu lub spłata/wykreślenie zabezpieczonego zobowiązania'],
    blocksApplication: true,
    evidence: ['umowa kredytu/zobowiązania', 'aktualne saldo i rachunek do spłaty', 'promesa/zgoda na wykreślenie hipoteki po spłacie', 'rodzaj oprocentowania, jeśli wymaga tego analiza'],
    canonicalKeys: ['loan.purpose', 'applicants.*.liabilities.*', 'property.mortgages.*'],
    notes: ['Załącznik PKO o zobowiązaniach wprost przewiduje dodatkowe zaświadczenie wierzyciela przed umową.'],
  },
  {
    id: 'pko-land-register-check',
    title: 'Weryfikacja księgi wieczystej i tytułu prawnego',
    method: 'bank_generated',
    scope: 'each_property',
    stage: 'property',
    requiredWhen: ['każda nieruchomość finansowana lub będąca zabezpieczeniem'],
    blocksApplication: true,
    evidence: ['bankowy wynik weryfikacji KW online', 'dokument tytułu prawnego/alternatywne dokumenty, jeśli KW nie istnieje'],
    canonicalKeys: ['property.landRegisterNumber', 'property.hasLandRegister', 'collateralProperties.*'],
    notes: ['Nie dodawać automatycznie pustego formularza.'],
  },
  {
    id: 'pko-property-valuation',
    title: 'Ocena wartości nieruchomości przez bank',
    method: 'bank_generated',
    scope: 'each_property',
    stage: 'property',
    requiredWhen: ['każda nieruchomość będąca zabezpieczeniem'],
    blocksApplication: true,
    evidence: ['bankowa ocena wartości', 'operat zlecony przez bank, jeśli przekroczono progi lub bank go wymaga'],
    canonicalKeys: ['property.marketValue', 'property.appraisalStatus', 'collateralProperties.*.marketValue'],
    notes: [
      'PKO BP zleca wymagany operat na swój koszt; klient nie musi go dostarczać. Operat klienta wymaga uprzedniej zgody i porozumienia co do rzeczoznawcy.',
      'PKO BH wykonuje własną bankowo-hipoteczną ekspertyzę i również nie wymaga operatu klienta.',
    ],
  },
  {
    id: 'pko-personalized-esis',
    title: 'Spersonalizowany formularz informacyjny / ESIS i symulacje',
    method: 'bank_generated',
    scope: 'case',
    stage: 'decision',
    requiredWhen: ['po wstępnej analizie oferty, przed związaniem klienta warunkami'],
    blocksApplication: false,
    evidence: ['bankowy formularz informacyjny z aktualną stopą i kosztami', 'symulacje rat i ryzyka przekazane klientowi', 'dowód doręczenia'],
    canonicalKeys: ['loan.offer.*', 'decision.*', 'informationDelivery.*'],
    notes: ['To dokument generowany dla konkretnej oferty; nie zastępować publicznym read-only PDF-em.'],
  },
  {
    id: 'pko-credit-decision-and-contract',
    title: 'Decyzja kredytowa i projekt umowy',
    method: 'bank_generated',
    scope: 'case',
    stage: 'decision',
    requiredWhen: ['po zakończeniu analizy banku'],
    blocksApplication: false,
    evidence: ['decyzja wskazująca PKO BP albo PKO BH jako kredytodawcę', 'projekt umowy', 'lista warunków do podpisania/wypłaty'],
    canonicalKeys: ['decision.*', 'loan.lender'],
    notes: ['Własny Kąt składa się do obu banków, ale decyzję i projekt umowy przekazuje tylko bank, który może udzielić kredytu.'],
  },
  {
    id: 'pko-notarial-sale-deed',
    title: 'Akt notarialny przenoszący własność',
    method: 'customer_upload',
    scope: 'case',
    stage: 'pre_disbursement',
    requiredWhen: ['warunek umowy dla finansowanego zakupu'],
    blocksApplication: false,
    evidence: ['akt notarialny sprzedaży/zamiany lub inny akt wymagany umową'],
    canonicalKeys: ['transaction.finalDeed.*'],
    notes: ['Nie blokuje złożenia wniosku, lecz może blokować uruchomienie kredytu.'],
  },
  {
    id: 'pko-mortgage-court-filing',
    title: 'Wniosek sądowy o wpis/założenie KW i hipotekę',
    method: 'customer_upload',
    scope: 'each_property',
    stage: 'pre_disbursement',
    requiredWhen: ['warunek umowy przed wypłatą lub po wypłacie w terminie umownym'],
    blocksApplication: false,
    evidence: ['kopia wniosku do sądu', 'potwierdzenie opłaty sądowej'],
    canonicalKeys: ['property.mortgageRegistration.*'],
    notes: ['Termin i dokładny zakres wynikają z decyzji/umowy.'],
  },
  {
    id: 'pko-property-insurance-assignment',
    title: 'Ubezpieczenie nieruchomości z cesją na bank',
    method: 'customer_upload',
    scope: 'each_property',
    stage: 'pre_disbursement',
    requiredWhen: ['zabudowana nieruchomość stanowi zabezpieczenie, chyba że umowa przewiduje wyjątek'],
    blocksApplication: false,
    evidence: ['polisa obejmująca co najmniej pożar, zalanie i powódź', 'cesja/przelew wierzytelności na właściwy bank'],
    canonicalKeys: ['property.insurance.*', 'loan.lender'],
    notes: ['Standardowe zabezpieczenie wymagane przez informacje ogólne; można skorzystać z oferty pośredniczonej przez PKO BP.'],
  },
  {
    id: 'pko-construction-completion-evidence',
    title: 'Dokumenty zakończenia budowy i użytkowania',
    method: 'customer_upload',
    scope: 'case',
    stage: 'post_contract',
    requiredWhen: ['umowa budowlana wymaga potwierdzenia ukończenia lub ujawnienia budynku'],
    blocksApplication: false,
    evidence: ['zgłoszenie zakończenia budowy/pozwolenie na użytkowanie', 'wypis z rejestru gruntów i budynków lub dokument odbioru, jeżeli wskazany w umowie'],
    canonicalKeys: ['property.construction.completion.*'],
    notes: ['To warunki po umowie, nie brak pierwotnej paczki wniosku.'],
  },
  {
    id: 'pko-energy-certificate-green-margin',
    title: 'Świadectwo charakterystyki energetycznej dla obniżki marży',
    method: 'customer_upload',
    scope: 'each_property',
    stage: 'post_contract',
    requiredWhen: ['klient chce skorzystać z zielonej obniżki marży po zawarciu umowy Własny Kąt'],
    blocksApplication: false,
    evidence: ['ważne świadectwo spełniające progi EP i pozostałe warunki bieżącej promocji'],
    canonicalKeys: ['property.energyCertificate.*', 'loan.greenMarginRequested'],
    notes: ['Nie wymagać do złożenia wniosku; publiczna strona wskazuje dostarczenie po zawarciu umowy.'],
  },
] as const satisfies readonly PkoCaseRequirement[]

/** Canonical data still required before the supplemental active PDFs can be mapped. */
export const PKO_MISSING_CANONICAL_KEYS = {
  packageRouting: [
    'application.submissionChannel',
    'application.hasLiabilitiesToRepay',
    'application.hasOtherResidentialProperties',
    'property.requiresMortgageDischargeAnnex',
    'property.costEstimateType',
    'applicants.*.employmentEvidenceType',
    'loan.pkoRoute',
    'loan.lender',
    'postContract.familyRepaymentRequested',
  ],
  applicantAnnex: [
    'applicants.*.identityDocumentIssueDate',
    'applicants.*.identityDocumentExpiryDate',
    'applicants.*.motherMaidenName',
    'applicants.*.birthSurname',
    'applicants.*.motherFirstName',
    'applicants.*.countryOfCurrentStay',
    'applicants.*.alternatePhone',
    'applicants.*.maritalPropertySeparation',
    'applicants.*.dependantsCount',
    'applicants.*.otherIncomeSourceText',
    'applicants.*.noIncomeSource',
    'applicants.*.otherFinancialObligationsDescription',
    'applicants.*.consumerLeaseMonthlyPayments',
    'applicants.*.paydayLoanMonthlyPayments',
    'applicants.*.paydayLoanLimits',
    'applicants.*.enforcementProceedings',
    'applicants.*.consumerBankruptcyFiled',
    'applicants.*.zusKrusArrears',
    'applicants.*.taxOfficeArrears',
    'applicants.*.consents.*',
  ],
  ownedProperties: [
    'ownedResidentialProperties.*.usableArea',
    'ownedResidentialProperties.*.ownerApplicantNumbers',
    'ownedResidentialProperties.*.revenueCoversCosts',
    'ownedResidentialProperties.*.monthlyMaintenanceCost',
  ],
  mortgageAnnex: [
    'property.mortgages.*.amount',
    'property.mortgages.*.currency',
    'property.mortgages.*.creditor',
    'property.mortgages.*.emptyPlaceApplicable',
    'property.mortgages.*.replacementClaim',
    'property.mortgages.*.multipleSecuredClaims',
  ],
  costEstimate: [
    'property.construction.*',
    'investment.costEstimate.lineItems.*',
    'investment.costEstimate.currentAdvancement',
    'investment.costEstimate.remainingCost',
    'property.energySource',
    'property.heatingSource',
    'property.waterSource',
  ],
  rkm: [
    'applicants.*.rkmEligibility.*',
    'households.*.country',
    'households.*.citizenshipCondition',
    'rkm.previousMortgageException.*',
    'rkm.otherFamilyMortgage.*',
    'rkm.propertyOwnershipException.*',
    'rkm.donations.*',
    'rkm.pricePerSquareMeterLimit',
    'rkm.ownContributionRatio',
    'rkm.guarantee.amount',
    'rkm.guarantee.percentage',
    'rkm.guarantee.periodMonths',
    'rkm.bgkConsents.*',
  ],
} as const
